-- ============================================================
-- TAHAP 3 / 1 — Deklarasi FK relasi implisit + index kolom FK
-- Dibuat  : php artisan siklik:audit-skema (2026-09-11 08:42)
-- VALIDATE = semua baris lama cocok. NOVALIDATE = ada baris yatim; hanya baris baru/ubah yang dijaga (legacy siklik-lite ikut terjaga).
-- ============================================================
SET DEFINE OFF
SET SQLBLANKLINES ON
SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

-- LEWATI INSTALL_TOKOKU.ID_EX → SKMST_EX_IMS : tabel warisan di luar aplikasi
-- SKACC_CARABAYARS.ACC_ID → SKACC_ACCOUNTSES.ACC_ID  (5 baris, 0 yatim)
CREATE INDEX CARABAYARS_ACC_IX ON SKACC_CARABAYARS (ACC_ID);
ALTER TABLE SKACC_CARABAYARS ADD CONSTRAINT CARABAYARS_ACC_FK FOREIGN KEY (ACC_ID) REFERENCES SKACC_ACCOUNTSES (ACC_ID) ENABLE VALIDATE;

-- LEWATI SKMST_ACCDOCOTHERS.ACCDOC_ID → SKMST_ACCDOCS : SEMUA baris yatim — kemungkinan bukan relasi nyata, periksa manual
-- SKMST_ACCDOCOTHERS.OTHER_ID → SKMST_OTHERS.OTHER_ID  (1 baris, 0 yatim)
CREATE INDEX ACCDOCOTHERS_OTHER_IX ON SKMST_ACCDOCOTHERS (OTHER_ID);
ALTER TABLE SKMST_ACCDOCOTHERS ADD CONSTRAINT ACCDOCOTHERS_OTHER_FK FOREIGN KEY (OTHER_ID) REFERENCES SKMST_OTHERS (OTHER_ID) ENABLE VALIDATE;

-- SKMST_ACCDOCPRODUCTS.ACCDOC_ID → SKMST_ACCDOCS.ACCDOC_ID  (0 baris, 0 yatim)
CREATE INDEX ACCDOCPRODUCTS_ACCDOC_IX ON SKMST_ACCDOCPRODUCTS (ACCDOC_ID);
ALTER TABLE SKMST_ACCDOCPRODUCTS ADD CONSTRAINT ACCDOCPRODUCTS_ACCDOC_FK FOREIGN KEY (ACCDOC_ID) REFERENCES SKMST_ACCDOCS (ACCDOC_ID) ENABLE VALIDATE;

-- SKMST_ACTEPRODS.ACTE_ID → SKMST_ACTEMPS.ACTE_ID  (0 baris, 0 yatim)
CREATE INDEX ACTEPRODS_ACTE_IX ON SKMST_ACTEPRODS (ACTE_ID);
ALTER TABLE SKMST_ACTEPRODS ADD CONSTRAINT ACTEPRODS_ACTE_FK FOREIGN KEY (ACTE_ID) REFERENCES SKMST_ACTEMPS (ACTE_ID) ENABLE VALIDATE;

-- SKMST_ACTPAROTHERS.OTHER_ID → SKMST_OTHERS.OTHER_ID  (0 baris, 0 yatim)
CREATE INDEX ACTPAROTHERS_OTHER_IX ON SKMST_ACTPAROTHERS (OTHER_ID);
ALTER TABLE SKMST_ACTPAROTHERS ADD CONSTRAINT ACTPAROTHERS_OTHER_FK FOREIGN KEY (OTHER_ID) REFERENCES SKMST_OTHERS (OTHER_ID) ENABLE VALIDATE;

-- SKMST_ACTPAROTHERS.PACT_ID → SKMST_ACTPARAMEDICS.PACT_ID  (0 baris, 0 yatim)
CREATE INDEX ACTPAROTHERS_PACT_IX ON SKMST_ACTPAROTHERS (PACT_ID);
ALTER TABLE SKMST_ACTPAROTHERS ADD CONSTRAINT ACTPAROTHERS_PACT_FK FOREIGN KEY (PACT_ID) REFERENCES SKMST_ACTPARAMEDICS (PACT_ID) ENABLE VALIDATE;

-- SKMST_ACTPARPRODUCTS.PACT_ID → SKMST_ACTPARAMEDICS.PACT_ID  (0 baris, 0 yatim)
CREATE INDEX ACTPARPRODUCTS_PACT_IX ON SKMST_ACTPARPRODUCTS (PACT_ID);
ALTER TABLE SKMST_ACTPARPRODUCTS ADD CONSTRAINT ACTPARPRODUCTS_PACT_FK FOREIGN KEY (PACT_ID) REFERENCES SKMST_ACTPARAMEDICS (PACT_ID) ENABLE VALIDATE;

-- SKMST_CLABITEMS.LOINC_CODE → SKMST_LOINC_CODES.LOINC_CODE  (108 baris, 1 yatim)
ALTER TABLE SKMST_CLABITEMS ADD CONSTRAINT CLABITEMS_LOINC_CODE_FK FOREIGN KEY (LOINC_CODE) REFERENCES SKMST_LOINC_CODES (LOINC_CODE) ENABLE NOVALIDATE;

-- SKMST_CUSTOMERS.PROV_ID → SKMST_PROVS.PROV_ID  (7 baris, 0 yatim)
CREATE INDEX CUSTOMERS_PROV_IX ON SKMST_CUSTOMERS (PROV_ID);
ALTER TABLE SKMST_CUSTOMERS ADD CONSTRAINT CUSTOMERS_PROV_FK FOREIGN KEY (PROV_ID) REFERENCES SKMST_PROVS (PROV_ID) ENABLE VALIDATE;

-- SKMST_PRODUCTCONTENTS.UOM_ID → SKMST_UOMS.UOM_ID  (0 baris, 0 yatim)
ALTER TABLE SKMST_PRODUCTCONTENTS ADD CONSTRAINT PRODUCTCONTENTS_UOM_FK FOREIGN KEY (UOM_ID) REFERENCES SKMST_UOMS (UOM_ID) ENABLE VALIDATE;

-- SKMST_PRODUCTNONS.UOM_ID → SKMST_UOMS.UOM_ID  (0 baris, 0 yatim)
CREATE INDEX PRODUCTNONS_UOM_IX ON SKMST_PRODUCTNONS (UOM_ID);
ALTER TABLE SKMST_PRODUCTNONS ADD CONSTRAINT PRODUCTNONS_UOM_FK FOREIGN KEY (UOM_ID) REFERENCES SKMST_UOMS (UOM_ID) ENABLE VALIDATE;

-- SKMST_RADIOLOGIS.LOINC_CODE → SKMST_LOINC_CODES.LOINC_CODE  (127 baris, 0 yatim)
ALTER TABLE SKMST_RADIOLOGIS ADD CONSTRAINT RADIOLOGIS_LOINC_CODE_FK FOREIGN KEY (LOINC_CODE) REFERENCES SKMST_LOINC_CODES (LOINC_CODE) ENABLE VALIDATE;

-- SKMST_SCPOLIS.DAY_ID → SKMST_SCDAYS.DAY_ID  (0 baris, 0 yatim)
CREATE INDEX SCPOLIS_DAY_IX ON SKMST_SCPOLIS (DAY_ID);
ALTER TABLE SKMST_SCPOLIS ADD CONSTRAINT SCPOLIS_DAY_FK FOREIGN KEY (DAY_ID) REFERENCES SKMST_SCDAYS (DAY_ID) ENABLE VALIDATE;

-- SKMST_SCPOLIS.DR_ID → SKMST_DOCTORS.DR_ID  (0 baris, 0 yatim)
CREATE INDEX SCPOLIS_DR_IX ON SKMST_SCPOLIS (DR_ID);
ALTER TABLE SKMST_SCPOLIS ADD CONSTRAINT SCPOLIS_DR_FK FOREIGN KEY (DR_ID) REFERENCES SKMST_DOCTORS (DR_ID) ENABLE VALIDATE;

-- SKMST_SCPOLIS.POLI_ID → SKMST_POLIS.POLI_ID  (0 baris, 0 yatim)
ALTER TABLE SKMST_SCPOLIS ADD CONSTRAINT SCPOLIS_POLI_FK FOREIGN KEY (POLI_ID) REFERENCES SKMST_POLIS (POLI_ID) ENABLE VALIDATE;

-- SKTXN_CASHOUTHDRNONS.CB_ID → SKACC_CARABAYARS.CB_ID  (0 baris, 0 yatim)
CREATE INDEX CASHOUTHDRNONS_CB_IX ON SKTXN_CASHOUTHDRNONS (CB_ID);
ALTER TABLE SKTXN_CASHOUTHDRNONS ADD CONSTRAINT CASHOUTHDRNONS_CB_FK FOREIGN KEY (CB_ID) REFERENCES SKACC_CARABAYARS (CB_ID) ENABLE VALIDATE;

-- SKTXN_CASHOUTHDRNONS.KASIR_ID → SKMST_KASIRS.KASIR_ID  (0 baris, 0 yatim)
CREATE INDEX CASHOUTHDRNONS_KASIR_IX ON SKTXN_CASHOUTHDRNONS (KASIR_ID);
ALTER TABLE SKTXN_CASHOUTHDRNONS ADD CONSTRAINT CASHOUTHDRNONS_KASIR_FK FOREIGN KEY (KASIR_ID) REFERENCES SKMST_KASIRS (KASIR_ID) ENABLE VALIDATE;

-- SKTXN_CASHOUTHDRNONS.SUPP_ID → SKMST_SUPPLIERS.SUPP_ID  (0 baris, 0 yatim)
CREATE INDEX CASHOUTHDRNONS_SUPP_IX ON SKTXN_CASHOUTHDRNONS (SUPP_ID);
ALTER TABLE SKTXN_CASHOUTHDRNONS ADD CONSTRAINT CASHOUTHDRNONS_SUPP_FK FOREIGN KEY (SUPP_ID) REFERENCES SKMST_SUPPLIERS (SUPP_ID) ENABLE VALIDATE;

-- SKTXN_CHECKUPDTLS.CHECKUP_NO → SKTXN_CHECKUPHDRS.CHECKUP_NO  (5825 baris, 0 yatim)
ALTER TABLE SKTXN_CHECKUPDTLS ADD CONSTRAINT CHECKUPDTLS_CHECKUP_NO_FK FOREIGN KEY (CHECKUP_NO) REFERENCES SKTXN_CHECKUPHDRS (CHECKUP_NO) ENABLE VALIDATE;

-- SKTXN_CHECKUPHDRS.REG_NO → SKMST_PASIENS.REG_NO  (225 baris, 0 yatim)
ALTER TABLE SKTXN_CHECKUPHDRS ADD CONSTRAINT CHECKUPHDRS_REG_NO_FK FOREIGN KEY (REG_NO) REFERENCES SKMST_PASIENS (REG_NO) ENABLE VALIDATE;

-- SKTXN_CHECKUPOBATS.CHECKUP_NO → SKTXN_CHECKUPHDRS.CHECKUP_NO  (6 baris, 0 yatim)
ALTER TABLE SKTXN_CHECKUPOBATS ADD CONSTRAINT CHECKUPOBATS_CHECKUP_NO_FK FOREIGN KEY (CHECKUP_NO) REFERENCES SKTXN_CHECKUPHDRS (CHECKUP_NO) ENABLE VALIDATE;

-- SKTXN_RCVHDRNONS.CB_ID → SKACC_CARABAYARS.CB_ID  (0 baris, 0 yatim)
CREATE INDEX RCVHDRNONS_CB_IX ON SKTXN_RCVHDRNONS (CB_ID);
ALTER TABLE SKTXN_RCVHDRNONS ADD CONSTRAINT RCVHDRNONS_CB_FK FOREIGN KEY (CB_ID) REFERENCES SKACC_CARABAYARS (CB_ID) ENABLE VALIDATE;

-- SKTXN_RCVHDRNONS.KASIR_ID → SKMST_KASIRS.KASIR_ID  (0 baris, 0 yatim)
CREATE INDEX RCVHDRNONS_KASIR_IX ON SKTXN_RCVHDRNONS (KASIR_ID);
ALTER TABLE SKTXN_RCVHDRNONS ADD CONSTRAINT RCVHDRNONS_KASIR_FK FOREIGN KEY (KASIR_ID) REFERENCES SKMST_KASIRS (KASIR_ID) ENABLE VALIDATE;

-- SKTXN_RCVHDRNONS.SUPP_ID → SKMST_SUPPLIERS.SUPP_ID  (0 baris, 0 yatim)
CREATE INDEX RCVHDRNONS_SUPP_IX ON SKTXN_RCVHDRNONS (SUPP_ID);
ALTER TABLE SKTXN_RCVHDRNONS ADD CONSTRAINT RCVHDRNONS_SUPP_FK FOREIGN KEY (SUPP_ID) REFERENCES SKMST_SUPPLIERS (SUPP_ID) ENABLE VALIDATE;

-- SKTXN_RJACCDOCS.ACCDOC_ID → SKMST_ACCDOCS.ACCDOC_ID  (358 baris, 1 yatim)
ALTER TABLE SKTXN_RJACCDOCS ADD CONSTRAINT RJACCDOCS_ACCDOC_FK FOREIGN KEY (ACCDOC_ID) REFERENCES SKMST_ACCDOCS (ACCDOC_ID) ENABLE NOVALIDATE;

-- SKTXN_RJACCDOCS.RJ_NO → SKTXN_RJHDRS.RJ_NO  (358 baris, 0 yatim)
ALTER TABLE SKTXN_RJACCDOCS ADD CONSTRAINT RJACCDOCS_RJ_NO_FK FOREIGN KEY (RJ_NO) REFERENCES SKTXN_RJHDRS (RJ_NO) ENABLE VALIDATE;

-- SKTXN_RJACTEMPS.ACTE_ID → SKMST_ACTEMPS.ACTE_ID  (8335 baris, 0 yatim)
ALTER TABLE SKTXN_RJACTEMPS ADD CONSTRAINT RJACTEMPS_ACTE_FK FOREIGN KEY (ACTE_ID) REFERENCES SKMST_ACTEMPS (ACTE_ID) ENABLE VALIDATE;

-- SKTXN_RJACTEMPS.RJ_NO → SKTXN_RJHDRS.RJ_NO  (8335 baris, 0 yatim)
ALTER TABLE SKTXN_RJACTEMPS ADD CONSTRAINT RJACTEMPS_RJ_NO_FK FOREIGN KEY (RJ_NO) REFERENCES SKTXN_RJHDRS (RJ_NO) ENABLE VALIDATE;

-- SKTXN_RJDTLS.RJ_NO → SKTXN_RJHDRS.RJ_NO  (30328 baris, 0 yatim)
ALTER TABLE SKTXN_RJDTLS ADD CONSTRAINT RJDTLS_RJ_NO_FK FOREIGN KEY (RJ_NO) REFERENCES SKTXN_RJHDRS (RJ_NO) ENABLE VALIDATE;

-- SKTXN_RJHDRS.REG_NO → SKMST_PASIENS.REG_NO  (24001 baris, 0 yatim)
ALTER TABLE SKTXN_RJHDRS ADD CONSTRAINT RJHDRS_REG_NO_FK FOREIGN KEY (REG_NO) REFERENCES SKMST_PASIENS (REG_NO) ENABLE VALIDATE;

-- SKTXN_RJLABS.RJ_NO → SKTXN_RJHDRS.RJ_NO  (203 baris, 0 yatim)
ALTER TABLE SKTXN_RJLABS ADD CONSTRAINT RJLABS_RJ_NO_FK FOREIGN KEY (RJ_NO) REFERENCES SKTXN_RJHDRS (RJ_NO) ENABLE VALIDATE;

-- SKTXN_RJOBATRACIKANS.ACTE_DTL → SKTXN_RJACTEMPS.ACTE_DTL  (0 baris, 0 yatim)
CREATE INDEX RJOBATRACIKANS_ACTE_DTL_IX ON SKTXN_RJOBATRACIKANS (ACTE_DTL);
ALTER TABLE SKTXN_RJOBATRACIKANS ADD CONSTRAINT RJOBATRACIKANS_ACTE_DTL_FK FOREIGN KEY (ACTE_DTL) REFERENCES SKTXN_RJACTEMPS (ACTE_DTL) ENABLE VALIDATE;

-- LEWATI SKTXN_RJOBATRACIKANS.CATATAN → SKMST_SIGNA_CATATANS : teks signa bebas; SKMST_SIGNA_CATATANS hanya LOV saran
-- SKTXN_RJOBATRACIKANS.PACT_DTL → SKTXN_RJACTPARAMS.PACT_DTL  (0 baris, 0 yatim)
CREATE INDEX RJOBATRACIKANS_PACT_DTL_IX ON SKTXN_RJOBATRACIKANS (PACT_DTL);
ALTER TABLE SKTXN_RJOBATRACIKANS ADD CONSTRAINT RJOBATRACIKANS_PACT_DTL_FK FOREIGN KEY (PACT_DTL) REFERENCES SKTXN_RJACTPARAMS (PACT_DTL) ENABLE VALIDATE;

-- SKTXN_RJOBATRACIKANS.RJHN_DTL → SKTXN_RJACCDOCS.RJHN_DTL  (0 baris, 0 yatim)
CREATE INDEX RJOBATRACIKANS_RJHN_DTL_IX ON SKTXN_RJOBATRACIKANS (RJHN_DTL);
ALTER TABLE SKTXN_RJOBATRACIKANS ADD CONSTRAINT RJOBATRACIKANS_RJHN_DTL_FK FOREIGN KEY (RJHN_DTL) REFERENCES SKTXN_RJACCDOCS (RJHN_DTL) ENABLE VALIDATE;

-- SKTXN_RJOBATRACIKANS.RJOBAT_DTL → SKTXN_RJOBATS.RJOBAT_DTL  (10518 baris, 48 yatim)
CREATE INDEX RJOBATRACIKANS_RJOBAT_DTL_IX ON SKTXN_RJOBATRACIKANS (RJOBAT_DTL);
ALTER TABLE SKTXN_RJOBATRACIKANS ADD CONSTRAINT RJOBATRACIKANS_RJOBAT_DTL_FK FOREIGN KEY (RJOBAT_DTL) REFERENCES SKTXN_RJOBATS (RJOBAT_DTL) ENABLE NOVALIDATE;

-- SKTXN_RJOBATRACIKANS.RJ_NO → SKTXN_RJHDRS.RJ_NO  (10518 baris, 0 yatim)
CREATE INDEX RJOBATRACIKANS_RJ_NO_IX ON SKTXN_RJOBATRACIKANS (RJ_NO);
ALTER TABLE SKTXN_RJOBATRACIKANS ADD CONSTRAINT RJOBATRACIKANS_RJ_NO_FK FOREIGN KEY (RJ_NO) REFERENCES SKTXN_RJHDRS (RJ_NO) ENABLE VALIDATE;

-- SKTXN_RJOBATS.RJ_NO → SKTXN_RJHDRS.RJ_NO  (64851 baris, 0 yatim)
ALTER TABLE SKTXN_RJOBATS ADD CONSTRAINT RJOBATS_RJ_NO_FK FOREIGN KEY (RJ_NO) REFERENCES SKTXN_RJHDRS (RJ_NO) ENABLE VALIDATE;

-- SKTXN_SLSKIRIMS.PROV_ID → SKMST_PROVS.PROV_ID  (0 baris, 0 yatim)
CREATE INDEX SLSKIRIMS_PROV_IX ON SKTXN_SLSKIRIMS (PROV_ID);
ALTER TABLE SKTXN_SLSKIRIMS ADD CONSTRAINT SLSKIRIMS_PROV_FK FOREIGN KEY (PROV_ID) REFERENCES SKMST_PROVS (PROV_ID) ENABLE VALIDATE;

-- SKTXN_SOWHSNON.KASIR_ID → SKMST_KASIRS.KASIR_ID  (0 baris, 0 yatim)
CREATE INDEX SOWHSNON_KASIR_IX ON SKTXN_SOWHSNON (KASIR_ID);
ALTER TABLE SKTXN_SOWHSNON ADD CONSTRAINT SOWHSNON_KASIR_FK FOREIGN KEY (KASIR_ID) REFERENCES SKMST_KASIRS (KASIR_ID) ENABLE VALIDATE;

-- Index untuk FK yang sudah ada tapi kolomnya belum ber-index (cegah lock tabel anak saat induk diubah)
-- FK_CODTLNONS_HDR
CREATE INDEX CASHOUTDTLNONS_CASHOUT_NO_IX ON SKTXN_CASHOUTDTLNONS (CASHOUT_NO);
-- CASHOUTDTLS_CASHOUT_NO_FK
CREATE INDEX CASHOUTDTLS_CASHOUT_NO_IX ON SKTXN_CASHOUTDTLS (CASHOUT_NO);
-- CASHOUTDTLS_RCV_NO_FK
CREATE INDEX CASHOUTDTLS_RCV_NO_IX ON SKTXN_CASHOUTDTLS (RCV_NO);
-- CASHOUTHDRS_CB_FK
CREATE INDEX CASHOUTHDRS_CB_IX ON SKTXN_CASHOUTHDRS (CB_ID);
-- CASHOUTHDRS_KASIR_FK
CREATE INDEX CASHOUTHDRS_KASIR_IX ON SKTXN_CASHOUTHDRS (KASIR_ID);
-- CASHOUTHDRS_SUPP_FK
CREATE INDEX CASHOUTHDRS_SUPP_IX ON SKTXN_CASHOUTHDRS (SUPP_ID);
-- FK_RCVDTLNONS_PRD
CREATE INDEX RCVDTLNONS_PRODUCT_IX ON SKTXN_RCVDTLNONS (PRODUCT_ID);
-- RCVDTLS_PRODUCT_FK
CREATE INDEX RCVDTLS_PRODUCT_IX ON SKTXN_RCVDTLS (PRODUCT_ID);
-- RCVDTLS_RCV_NO_FK
CREATE INDEX RCVDTLS_RCV_NO_IX ON SKTXN_RCVDTLS (RCV_NO);
-- RCVHDRS_CB_FK
CREATE INDEX RCVHDRS_CB_IX ON SKTXN_RCVHDRS (CB_ID);
-- RCVHDRS_KASIR_FK
CREATE INDEX RCVHDRS_KASIR_IX ON SKTXN_RCVHDRS (KASIR_ID);
-- RCVHDRS_SUPP_FK
CREATE INDEX RCVHDRS_SUPP_IX ON SKTXN_RCVHDRS (SUPP_ID);
-- FK_RCVPAYNONS_HDR
CREATE INDEX RCVPAYMENTNONS_RCV_NO_IX ON SKTXN_RCVPAYMENTNONS (RCV_NO);
-- RCVPAYMENTS_RCV_NO_FK
CREATE INDEX RCVPAYMENTS_RCV_NO_IX ON SKTXN_RCVPAYMENTS (RCV_NO);
-- RJACCDOCS_DR_FK
CREATE INDEX RJACCDOCS_DR_IX ON SKTXN_RJACCDOCS (DR_ID);
-- RJHDRS_KASIR_FK
CREATE INDEX RJHDRS_KASIR_IX ON SKTXN_RJHDRS (KASIR_ID);
-- FK_SALDONON_PRD
CREATE INDEX SALDOAWALSTOCKSNON_PRODUCT_IX ON SKTXN_SALDOAWALSTOCKSNON (PRODUCT_ID);
-- SOWHS_KASIR_FK
CREATE INDEX SOWHS_KASIR_IX ON SKTXN_SOWHS (KASIR_ID);
