-- ============================================================
-- TAHAP 3 / 2 — Drop objek PL/SQL INVALID (warisan bridging RS, sudah tidak bisa dieksekusi)
-- Dibuat  : php artisan siklik:audit-skema (2026-09-11 08:42)
-- Backup DDL: _backup_objek_invalid.sql. Jalankan HANYA setelah dipastikan tidak ada yang memakainya.
-- ============================================================
SET DEFINE OFF
SET SQLBLANKLINES ON
SET ECHO ON
WHENEVER SQLERROR CONTINUE

DROP FUNCTION CUSTOM_AUTH;
DROP PROCEDURE BRPROC_AREFHAPUSKMR;
DROP PROCEDURE BRPROC_AREFKELAS;
DROP PROCEDURE BRPROC_AREFTAMBAHKMR;
DROP PROCEDURE BRPROC_AREFUPDATEKMR;
DROP PROCEDURE BRPROC_CARI_KTSP;
DROP PROCEDURE BRPROC_CARI_NIK;
DROP PROCEDURE BRPROC_CARI_NORUJUKAN;
DROP PROCEDURE BRPROC_CARI_NORUJUKANNOKA;
DROP PROCEDURE BRPROC_CARI_SEP;
DROP PROCEDURE BRPROC_DELETERUJUKAN;
DROP PROCEDURE BRPROC_DELETESEP;
DROP PROCEDURE BRPROC_DIAGNOSA;
DROP PROCEDURE BRPROC_DPJP;
DROP PROCEDURE BRPROC_FASKES;
DROP PROCEDURE BRPROC_INSERTRUJUKAN;
DROP PROCEDURE BRPROC_INSERTSEP;
DROP PROCEDURE BRPROC_INSERT_TB;
DROP PROCEDURE BRPROC_KABUPATEN;
DROP PROCEDURE BRPROC_KECAMATAN;
DROP PROCEDURE BRPROC_POLI;
DROP PROCEDURE BRPROC_PROPINSI;
DROP PROCEDURE BRPROC_RIWAYATPESERTA;
DROP PROCEDURE BRPROC_UPDATERUJUKAN;
DROP PROCEDURE BRPROC_UPDATESEP;
DROP PROCEDURE BRPROC_UPDATETGLPULANG;
DROP PROCEDURE CUSTOM_IMAGE_DISPLAY;
