-- ============================================================
-- TAHAP 3 / 3 — Drop sequence yang tidak dirujuk kode/PL-SQL/trigger
-- Dibuat  : php artisan siklik:audit-skema (2026-09-11 08:42)
-- Nilai terakhir tercatat di 99_rollback.sql untuk CREATE ulang.
-- ============================================================
SET DEFINE OFF
SET SQLBLANKLINES ON
SET ECHO ON
WHENEVER SQLERROR CONTINUE

-- last_number 1
DROP SEQUENCE AA9_SEQ;
-- last_number 1
DROP SEQUENCE ACQ;
-- last_number 1
DROP SEQUENCE ACTXNASSETDTL_SEQ;
-- last_number 1
DROP SEQUENCE AUTOCUSTOMER_SEQ;
-- last_number 1
DROP SEQUENCE AUTOPRODUCT_SEQ;
-- last_number 1
DROP SEQUENCE AUTOSUPPLIER_SEQ;
-- last_number 1
DROP SEQUENCE CASHIN_SEQ;
-- last_number 1
DROP SEQUENCE CIDTL_SEQ;
-- last_number 1
DROP SEQUENCE DEBTDTL_SEQ;
-- last_number 1
DROP SEQUENCE DEBTHDR_SEQ;
-- last_number 21
DROP SEQUENCE DEMO_CUST_SEQ;
-- last_number 11
DROP SEQUENCE DEMO_IMAGES_SEQ;
-- last_number 21
DROP SEQUENCE DEMO_ORDER_ITEMS_SEQ;
-- last_number 11
DROP SEQUENCE DEMO_ORD_SEQ;
-- last_number 21
DROP SEQUENCE DEMO_USERS_SEQ;
-- last_number 1
DROP SEQUENCE ID_EX_SEQ;
-- last_number 1
DROP SEQUENCE JOURNALHDR_SEQ;
-- last_number 1
DROP SEQUENCE JOURNAL_SEQ;
-- last_number 1
DROP SEQUENCE KS2_SEQ;
-- last_number 1
DROP SEQUENCE LC4_1_SEQ_1;
-- last_number 1
DROP SEQUENCE LC4_SEQ_2;
-- last_number 1
DROP SEQUENCE LOANDTL_SEQ;
-- last_number 1
DROP SEQUENCE PAYDEBTDTL_SEQ;
-- last_number 1
DROP SEQUENCE PAYDEBTHDR_SEQ;
-- last_number 1
DROP SEQUENCE PRODNO;
-- last_number 1
DROP SEQUENCE RA1_SEQ;
-- last_number 1
DROP SEQUENCE RA2_SEQ;
-- last_number 1
DROP SEQUENCE RB1_SEQ_1;
-- last_number 1
DROP SEQUENCE RD2_SEQ;
-- last_number 1
DROP SEQUENCE RD_SEQ;
-- last_number 1
DROP SEQUENCE RECEIVEEDS_SEQ;
-- last_number 1
DROP SEQUENCE RIPAYPK_SEQ;
-- last_number 1
DROP SEQUENCE RIPAYP_SEQ;
-- last_number 1
DROP SEQUENCE RJCKDTL_SEQ;
-- last_number 1
DROP SEQUENCE RR3_SEQ_1;
-- last_number 1
DROP SEQUENCE SEQSTOCK;
-- last_number 1
DROP SEQUENCE SLSP_SEQ;
-- last_number 1
DROP SEQUENCE TEI_SEQ;
-- last_number 1
DROP SEQUENCE TS3_SEQ_1;
-- last_number 1
DROP SEQUENCE TUCASHD_SEQ;
-- last_number 1
DROP SEQUENCE TUCASHK_SEQ;
-- last_number 1
DROP SEQUENCE UGDCDTL_SEQ;
-- last_number 1
DROP SEQUENCE UGDOTHER_SEQ;
