-- ============================================================
-- LANGKAH 1 — CREATE TABLE + PK / UNIQUE / CHECK / komentar
-- Dibuat  : php artisan siklik:ddl-create  (2026-09-12 10:09)
-- Sumber  : data dictionary schema yang terhubung saat generate
-- Jalankan di schema kosong. Berhenti di error pertama.
-- ============================================================
SET DEFINE OFF
SET SQLBLANKLINES ON
SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE


-- ---------- Modul: Rawat Jalan ----------

CREATE TABLE SKTXN_RJACCDOCS (
    RJHN_DTL      NUMBER(10) NOT NULL,
    ACCDOC_ID     VARCHAR2(10) NOT NULL,
    RJ_NO         NUMBER(10) NOT NULL,
    ACCDOC_PRICE  NUMBER(9),
    DR_ID         VARCHAR2(9),
    CONSTRAINT RJACCDOCS_PK PRIMARY KEY (RJHN_DTL)
);
COMMENT ON COLUMN SKTXN_RJACCDOCS.DR_ID IS 'FK ??? RSMST_DOCTORS.DR_ID ??? dokter yg lakukan jasa medik di detail RJ';

CREATE TABLE SKTXN_RJACTEMPS (
    ACTE_ID     VARCHAR2(10) NOT NULL,
    ACTE_PRICE  NUMBER(9),
    RJ_NO       NUMBER(10) NOT NULL,
    ACTE_DTL    NUMBER(10) NOT NULL,
    CONSTRAINT RJACTEMPS_PK PRIMARY KEY (ACTE_DTL)
);

CREATE TABLE SKTXN_RJACTPARAMS (
    PACT_ID     VARCHAR2(10) NOT NULL,
    PACT_PRICE  NUMBER(9),
    PACT_DTL    NUMBER(10) NOT NULL,
    RJ_NO       NUMBER(10) NOT NULL,
    CONSTRAINT RJACTPARAMS_PK PRIMARY KEY (PACT_DTL)
);

CREATE TABLE SKTXN_RJCASHINS (
    RJC_DATE     DATE,
    RJC_NOMINAL  NUMBER(15,2),
    RJC_DTL      NUMBER(15) NOT NULL,
    RJC_DESC     VARCHAR2(100),
    RJ_NO        NUMBER(15) NOT NULL,
    CB_ID        VARCHAR2(25) NOT NULL,
    KASIR_ID     VARCHAR2(15) NOT NULL,
    SHIFT        VARCHAR2(5) NOT NULL,
    G_STATUS     VARCHAR2(3),
    CONSTRAINT RJCASHINS_PK PRIMARY KEY (RJC_DTL)
);

CREATE TABLE SKTXN_RJDTLS (
    RJDTL_DTL  NUMBER(10) NOT NULL,
    DIAG_ID    VARCHAR2(10) NOT NULL,
    RJ_NO      NUMBER(10) NOT NULL,
    CONSTRAINT RJDTLS_PK PRIMARY KEY (RJDTL_DTL)
);

CREATE TABLE SKTXN_RJHDRS (
    RJ_NO                    NUMBER(10) NOT NULL,
    RJ_DATE                  DATE,
    POLI_ID                  NUMBER(3) NOT NULL,
    DR_ID                    VARCHAR2(240) NOT NULL,
    REG_NO                   VARCHAR2(10) NOT NULL,
    RJ_TOTAL                 NUMBER(9),
    RJ_DISKON                NUMBER(9),
    RJ_STATUS                VARCHAR2(2),
    PASS_STATUS              VARCHAR2(2),
    ANAMNESIA                VARCHAR2(1000),
    CHECK_FISIK              VARCHAR2(1000),
    RJ_ADMIN                 NUMBER(9),
    POLI_PRICE               NUMBER(9),
    SL_CODEFROM              VARCHAR2(3),
    SHIFT                    VARCHAR2(5),
    CEK_LAB                  VARCHAR2(1),
    RJ_DIAGNOSA              VARCHAR2(2),
    STATUS_PULANG            VARCHAR2(5),
    KLAIM_ID                 VARCHAR2(5) NOT NULL,
    KASIR_ID                 VARCHAR2(15),
    CB_ID                    VARCHAR2(25),
    TXN_STATUS               VARCHAR2(3),
    PAY_DATE                 DATE,
    CEK_BAYAR                VARCHAR2(3),
    RS_ADMIN                 NUMBER(9),
    STATUS_LANJUTAN          VARCHAR2(10),
    VNO_SEP                  VARCHAR2(100),
    KETERANGAN_LANJUTAN      VARCHAR2(100),
    NO_ANTRIAN               NUMBER(15),
    WAKTU_MASUK_PELAYANAN    DATE,
    WAKTU_MASUK_APT          DATE,
    WAKTU_SELESAI_PELAYANAN  DATE,
    DATADAFTARPOLIRJ_JSON    CLOB,
    NOBOOKING                VARCHAR2(100),
    WAKTU_MASUK_POLI         DATE,
    ERM_STATUS               VARCHAR2(3),
    CONSTRAINT RJHDRS_PK PRIMARY KEY (RJ_NO)
);

CREATE TABLE SKTXN_RJLABS (
    LAB_DESC    VARCHAR2(100),
    LAB_DTL     NUMBER(9) NOT NULL,
    LAB_PRICE   NUMBER(9),
    RJ_NO       NUMBER(10) NOT NULL,
    CHECKUP_NO  NUMBER(10) NOT NULL,
    CONSTRAINT RJLABS_PK PRIMARY KEY (LAB_DTL)
);

CREATE TABLE SKTXN_RJOBATRACIKANS (
    RJOBAT_DTL      NUMBER(10) NOT NULL,
    QTY             NUMBER(9,2),
    PRICE           NUMBER(9),
    RJ_NO           NUMBER(10) NOT NULL,
    PRODUCT_ID      VARCHAR2(10),
    EXP_DATE        DATE,
    RJHN_DTL        NUMBER(15),
    ACTE_DTL        NUMBER(15),
    PACT_DTL        NUMBER(15),
    RJ_CARAPAKAI    VARCHAR2(25),
    RJ_TAKAR        VARCHAR2(50),
    RJ_KAPSUL       VARCHAR2(25),
    RJ_KET          VARCHAR2(100),
    ETIKET_STATUS   VARCHAR2(3),
    CATATAN_KHUSUS  VARCHAR2(250),
    PRODUCT_NAME    VARCHAR2(250),
    NO_RACIKAN      VARCHAR2(250),
    SEDIA           VARCHAR2(250),
    CATATAN         VARCHAR2(250),
    DOSIS           VARCHAR2(100)
);

CREATE TABLE SKTXN_RJOBATS (
    RJOBAT_DTL      NUMBER(10) NOT NULL,
    QTY             NUMBER(9,2),
    PRICE           NUMBER(9),
    RJ_NO           NUMBER(10) NOT NULL,
    PRODUCT_ID      VARCHAR2(10),
    EXP_DATE        DATE,
    RJHN_DTL        NUMBER(15),
    ACTE_DTL        NUMBER(15),
    PACT_DTL        NUMBER(15),
    RJ_CARAPAKAI    VARCHAR2(25),
    RJ_TAKAR        VARCHAR2(50),
    RJ_KAPSUL       VARCHAR2(25),
    RJ_KET          VARCHAR2(100),
    ETIKET_STATUS   VARCHAR2(3),
    CATATAN_KHUSUS  VARCHAR2(200),
    CONSTRAINT RJOBATS_PK PRIMARY KEY (RJOBAT_DTL)
);

CREATE TABLE SKTXN_RJOTHERS (
    RJO_DTL      NUMBER(15) NOT NULL,
    RJ_NO        NUMBER(15) NOT NULL,
    OTHER_ID     VARCHAR2(10),
    OTHER_PRICE  NUMBER(9),
    PACT_DTL     NUMBER(15),
    ACTE_DTL     NUMBER(15),
    RJHN_DTL     NUMBER(15),
    CONSTRAINT RJOTHERS_PK PRIMARY KEY (RJO_DTL)
);

CREATE TABLE SKTXN_RJRADS (
    RAD_PRICE       NUMBER(9),
    RAD_DTL         NUMBER(9) NOT NULL,
    RJ_NO           NUMBER(10) NOT NULL,
    RAD_ID          VARCHAR2(5) NOT NULL,
    KLINIS_DESC     VARCHAR2(4000),
    RAD_RESULT      VARCHAR2(4000),
    DR_RADIOLOGI    VARCHAR2(1000),
    RADNUM_NO       VARCHAR2(15),
    RAD_UPLOAD_PDF  VARCHAR2(100),
    KRITIS_STATUS   VARCHAR2(3),
    RAD_JM          NUMBER(15),
    WAKTU_ENTRY     DATE,
    CONSTRAINT RJRADS_PK PRIMARY KEY (RAD_DTL)
);

CREATE TABLE SKTXN_RJUPLOADBPJSES (
    JENIS_FILE  VARCHAR2(15),
    UPLOADBPJS  VARCHAR2(100) NOT NULL,
    RJ_NO       NUMBER(15) NOT NULL,
    SEQ_FILE    NUMBER(3),
    CONSTRAINT RJUPLOADBPJSES_PK PRIMARY KEY (UPLOADBPJS)
);

CREATE TABLE SKTXN_SHIFTCTLS (
    SHIFT         VARCHAR2(5),
    SHIFT_START   VARCHAR2(9),
    SHIFT_END     VARCHAR2(9),
    SHIFT_STARTX  VARCHAR2(9),
    SHIFT_ENDX    VARCHAR2(9),
    SHIFT_STARTK  VARCHAR2(9),
    SHIFT_ENDK    VARCHAR2(9)
);

-- ---------- Modul: Laboratorium ----------

CREATE TABLE SKMST_CLABITEMS (
    NORMAL_M        VARCHAR2(50),
    CLABITEM_DESC   VARCHAR2(100),
    IS_GROUP        VARCHAR2(10),
    PRICE           NUMBER(9),
    NORMAL_F        VARCHAR2(50),
    STATUS          VARCHAR2(10),
    CLABITEM_ID     VARCHAR2(10) NOT NULL,
    CLABITEM_GROUP  VARCHAR2(10),
    DOSAGE          NUMBER(9),
    CLAB_ID         VARCHAR2(5) NOT NULL,
    PRODUCT_ID      VARCHAR2(10) NOT NULL,
    ITEM_SEQ        NUMBER,
    UNIT_DESC       VARCHAR2(50),
    ITEM_CODE       VARCHAR2(25),
    LOWHIGH_STATUS  VARCHAR2(3),
    HIDDEN_STATUS   VARCHAR2(3),
    LOW_LIMIT_M     NUMBER(15,2),
    HIGH_LIMIT_M    NUMBER(15,2),
    LOW_LIMIT_F     NUMBER(15,2),
    HIGH_LIMIT_F    NUMBER(15,2),
    UNIT_CONVERT    NUMBER(15,2),
    LOINC_CODE      VARCHAR2(20),
    LOINC_DISPLAY   VARCHAR2(200),
    LOW_LIMIT_K     NUMBER(15,2),
    HIGH_LIMIT_K    NUMBER(15,2),
    CONSTRAINT CLABITEMS_PK PRIMARY KEY (CLABITEM_ID)
);
COMMENT ON COLUMN SKMST_CLABITEMS.LOINC_CODE IS 'Kode LOINC ??? paket header utk ServiceRequest/DiagnosticReport, item anak utk Observation';
COMMENT ON COLUMN SKMST_CLABITEMS.LOINC_DISPLAY IS 'Nama resmi LOINC (contoh: Hemoglobin [Mass/volume] in Blood)';
COMMENT ON COLUMN SKMST_CLABITEMS.LOW_LIMIT_K IS 'Batas bawah nilai normal untuk anak (Kid)';
COMMENT ON COLUMN SKMST_CLABITEMS.HIGH_LIMIT_K IS 'Batas atas nilai normal untuk anak (Kid)';

CREATE TABLE SKMST_CLABS (
    CLAB_DESC  VARCHAR2(50),
    CLAB_ID    VARCHAR2(5) NOT NULL,
    APP_SEQ    NUMBER(9),
    CONSTRAINT CLABS_PK PRIMARY KEY (CLAB_ID)
);

CREATE TABLE SKTXN_CHECKUPDTLS (
    LAB_RESULT         VARCHAR2(100),
    PRICE              NUMBER(9,2),
    CHECKUP_DTL        NUMBER(10) NOT NULL,
    CLABITEM_ID        VARCHAR2(10) NOT NULL,
    CHECKUP_NO         NUMBER(10) NOT NULL,
    LAB_RESULT_STATUS  VARCHAR2(3),
    LAB_ITEM_CODE      VARCHAR2(100),
    CONSTRAINT CHECKUPDTLS_PK PRIMARY KEY (CHECKUP_DTL)
);

CREATE TABLE SKTXN_CHECKUPHDRS (
    CHECKUP_NO               NUMBER(10) NOT NULL,
    CHECKUP_DATE             DATE,
    REG_NO                   VARCHAR2(10) NOT NULL,
    DR_ID                    VARCHAR2(9) NOT NULL,
    CHECKUP_STATUS           VARCHAR2(3),
    STATUS_RJRI              VARCHAR2(5),
    REF_NO                   NUMBER(9),
    KASIR_ID                 VARCHAR2(15),
    PATIENT_NAME             VARCHAR2(100),
    WAKTU_MASUK_PELAYANAN    DATE,
    WAKTU_SELESAI_PELAYANAN  DATE,
    KLINIS_DESC              VARCHAR2(500),
    CONSTRAINT CHECKUPHDRS_PK PRIMARY KEY (CHECKUP_NO)
);
COMMENT ON COLUMN SKTXN_CHECKUPHDRS.KLINIS_DESC IS 'Diagnosis kerja / keterangan klinis order laboratorium ¿ wajib diisi dokter di form order EMR';

CREATE TABLE SKTXN_CHECKUPOBATS (
    CHECKUP_NO  NUMBER(10) NOT NULL,
    PRODUCT_ID  VARCHAR2(10),
    QTY         NUMBER(9,2),
    PRICE       NUMBER,
    ID          NUMBER(15) NOT NULL,
    CONSTRAINT CHECKUPOBATS_PK PRIMARY KEY (ID)
);

CREATE TABLE SKTXN_CHECKUPOUTDTLS (
    LABOUT_RESULT  VARCHAR2(1000),
    LABOUT_PRICE   NUMBER(15),
    LABOUT_NORMAL  VARCHAR2(1000),
    LABOUT_DTL     NUMBER(15) NOT NULL,
    LABOUT_DESC    VARCHAR2(1000),
    CHECKUP_NO     NUMBER(15) NOT NULL,
    CONSTRAINT CHECKUPOUTDTLS_PK PRIMARY KEY (LABOUT_DTL)
);

-- ---------- Modul: Pasien & Klinik ----------

CREATE TABLE SKMST_DOCTORS (
    DR_ID                VARCHAR2(9) NOT NULL,
    DR_ADDRESS           VARCHAR2(100),
    DR_PHONE             VARCHAR2(15),
    DR_NAME              VARCHAR2(50),
    POLI_ID              NUMBER(3) NOT NULL,
    POLI_PRICE           NUMBER,
    UGD_PRICE            NUMBER(9),
    BASIC_SALARY         NUMBER(15),
    CONTRIBUTION_STATUS  VARCHAR2(2),
    ACTIVE_STATUS        VARCHAR2(3),
    RS_ADMIN             NUMBER(9),
    DR_UUID              VARCHAR2(100),
    KD_DR_BPJS           VARCHAR2(100),
    DR_NIK               VARCHAR2(100),
    CONSTRAINT DOCTORS_PK PRIMARY KEY (DR_ID)
);

CREATE TABLE SKMST_EDUCATIONS (
    EDU_DESC  VARCHAR2(25),
    EDU_ID    NUMBER(2) NOT NULL,
    CONSTRAINT EDUCATIONS_PK PRIMARY KEY (EDU_ID)
);

CREATE TABLE SKMST_ENTRYTYPES (
    ENTRY_ID    VARCHAR2(3) NOT NULL,
    ENTRY_DESC  VARCHAR2(50),
    CONSTRAINT ENTRYTYPES_PK PRIMARY KEY (ENTRY_ID)
);

CREATE TABLE SKMST_JOBS (
    JOB_ID    NUMBER(2) NOT NULL,
    JOB_NAME  VARCHAR2(25),
    CONSTRAINT JOBS_PK PRIMARY KEY (JOB_ID)
);

CREATE TABLE SKMST_KLAIMTYPES (
    KLAIM_ID      VARCHAR2(5) NOT NULL,
    KLAIM_DESC    VARCHAR2(50),
    KLAIM_STATUS  VARCHAR2(15),
    CONSTRAINT KLAIMTYPES_PK PRIMARY KEY (KLAIM_ID)
);

CREATE TABLE SKMST_MEDIK (
    CONDITION   VARCHAR2(20),
    JML         NUMBER(9),
    KAPASITI    VARCHAR2(20),
    AGE         NUMBER(20),
    MEDIK_NO    VARCHAR2(20) NOT NULL,
    SERTIFIKAT  VARCHAR2(20),
    TGL_BUY     DATE,
    IZIN        VARCHAR2(20),
    MEDIK_NAME  VARCHAR2(200),
    BLN         NUMBER(9),
    CONSTRAINT MEDIK_PK PRIMARY KEY (MEDIK_NO)
);

CREATE TABLE SKMST_MSTDIAGS (
    DIAG_ID    VARCHAR2(10) NOT NULL,
    DIAG_DESC  VARCHAR2(250),
    ICDX       VARCHAR2(100),
    CONSTRAINT MSTDIAGS_PK PRIMARY KEY (DIAG_ID)
);

CREATE TABLE SKMST_MSTPROCEDURES (
    PROC_ID    VARCHAR2(15) NOT NULL,
    PROC_DESC  VARCHAR2(250),
    CONSTRAINT MSTPROCEDURES_PK PRIMARY KEY (PROC_ID)
);

CREATE TABLE SKMST_OTHERS (
    OTHER_ID       VARCHAR2(15) NOT NULL,
    OTHER_DESC     VARCHAR2(50),
    OTHER_PRICE    NUMBER(9),
    ACTIVE_STATUS  VARCHAR2(3),
    CONSTRAINT OTHERS_PK PRIMARY KEY (OTHER_ID)
);

CREATE TABLE SKMST_OUTS (
    OUT_NO    VARCHAR2(5) NOT NULL,
    OUT_DESC  VARCHAR2(50),
    CONSTRAINT OUTS_PK PRIMARY KEY (OUT_NO)
);

CREATE TABLE SKMST_PASIENS (
    REG_DATE               DATE,
    BLOOD                  VARCHAR2(2),
    RT                     VARCHAR2(4),
    ADDRESS                VARCHAR2(100),
    MARITAL_STATUS         VARCHAR2(2),
    BIRTH_PLACE            VARCHAR2(50),
    RW                     VARCHAR2(4),
    REG_NO                 VARCHAR2(10) NOT NULL,
    SEX                    VARCHAR2(2),
    REG_NAME               VARCHAR2(50),
    BIRTH_DATE             DATE,
    PHONE                  VARCHAR2(15),
    DES_ID                 NUMBER(10) NOT NULL,
    JOB_ID                 NUMBER(2) NOT NULL,
    REL_ID                 NUMBER(2) NOT NULL,
    KAB_ID                 NUMBER(10) NOT NULL,
    PROP_ID                NUMBER(10) NOT NULL,
    KEC_ID                 NUMBER(10) NOT NULL,
    EDU_ID                 NUMBER(2) NOT NULL,
    THN                    NUMBER(3),
    BLN                    NUMBER(3),
    HARI                   NUMBER(3),
    LOCKSTATUS             VARCHAR2(3),
    KK                     VARCHAR2(100),
    NYONYA                 VARCHAR2(100),
    NO_KK                  VARCHAR2(50),
    NO_JKN                 VARCHAR2(50),
    ALERGY_DESC            VARCHAR2(100),
    NOKARTU_BPJS           VARCHAR2(100),
    NIK_BPJS               VARCHAR2(100),
    ID_TB_03               VARCHAR2(100),
    META_DATA_PASIEN_JSON  CLOB,
    PATIENT_UUID           VARCHAR2(100),
    CONSTRAINT PASIENS_PK PRIMARY KEY (REG_NO)
);

CREATE TABLE SKMST_POLIS (
    POLI_ID       NUMBER(3) NOT NULL,
    POLI_DESC     VARCHAR2(50),
    POLI_UUID     VARCHAR2(100),
    KD_POLI_BPJS  VARCHAR2(100),
    CONSTRAINT POLIS_PK PRIMARY KEY (POLI_ID)
);

CREATE TABLE SKMST_RADIOLOGIS (
    RAD_ID         VARCHAR2(5) NOT NULL,
    RAD_PRICE      NUMBER(9),
    RAD_DESC       VARCHAR2(50),
    ACTIVE_STATUS  VARCHAR2(3),
    RAD_JD         NUMBER(9),
    LOINC_CODE     VARCHAR2(20),
    LOINC_DISPLAY  VARCHAR2(200),
    CONSTRAINT RADIOLOGIS_PK PRIMARY KEY (RAD_ID)
);
COMMENT ON COLUMN SKMST_RADIOLOGIS.LOINC_CODE IS 'Kode LOINC ??? utk ServiceRequest/DiagnosticReport radiologi ke Satu Sehat';
COMMENT ON COLUMN SKMST_RADIOLOGIS.LOINC_DISPLAY IS 'Nama resmi LOINC (contoh: XR Chest 2 Views)';

CREATE TABLE SKMST_RELIGIONS (
    REL_DESC  VARCHAR2(15),
    REL_ID    NUMBER(2) NOT NULL,
    CONSTRAINT RELIGIONS_PK PRIMARY KEY (REL_ID)
);

CREATE TABLE SKMST_SCDAYS (
    DAY_ID    NUMBER(1) NOT NULL,
    DAY_DESC  VARCHAR2(20),
    CONSTRAINT SCDAYS_PK PRIMARY KEY (DAY_ID)
);

CREATE TABLE SKMST_SCPOLIS (
    SC_POLI_STATUS_       VARCHAR2(3),
    SC_POLI_KET           VARCHAR2(50),
    DAY_ID                NUMBER(1) NOT NULL,
    POLI_ID               NUMBER NOT NULL,
    DR_ID                 VARCHAR2(15) NOT NULL,
    SHIFT                 NUMBER(1),
    MULAI_PRAKTEK         VARCHAR2(8),
    PELAYANAN_PERP_ASIEN  NUMBER,
    NO_URUT               NUMBER,
    KUOTA                 NUMBER,
    SELESAI_PRAKTEK       VARCHAR2(8)
);

-- ---------- Modul: Tarif & Jasa ----------

CREATE TABLE SKMST_ACCDOCOTHERS (
    ACCDOTHER_PRICE  NUMBER(15),
    ACCDOC_ID        VARCHAR2(15) NOT NULL,
    OTHER_ID         VARCHAR2(15) NOT NULL
);

CREATE TABLE SKMST_ACCDOCPRODUCTS (
    ACCDPROD_QTY  NUMBER(15),
    ACCDOC_ID     VARCHAR2(15) NOT NULL,
    PRODUCT_ID    VARCHAR2(50) NOT NULL
);

CREATE TABLE SKMST_ACCDOCS (
    ACCDOC_ID      VARCHAR2(10) NOT NULL,
    ACCDOC_DESC    VARCHAR2(50),
    ACCDOC_PRICE   NUMBER(9),
    ACTIVE_STATUS  VARCHAR2(3),
    CONSTRAINT ACCDOCS_PK PRIMARY KEY (ACCDOC_ID)
);

CREATE TABLE SKMST_ACTEMPS (
    ACTE_ID        VARCHAR2(10) NOT NULL,
    ACTE_DESC      VARCHAR2(100),
    ACTE_PRICE     NUMBER(9),
    ACTIVE_STATUS  VARCHAR2(3),
    CONSTRAINT ACTEMPS_PK PRIMARY KEY (ACTE_ID)
);

CREATE TABLE SKMST_ACTEOTHERS (
    ACTEOTHER_PRICE  NUMBER(15),
    ACTE_ID          VARCHAR2(15) NOT NULL,
    OTHER_ID         VARCHAR2(15) NOT NULL,
    CONSTRAINT ACTEOTHERS_PK PRIMARY KEY (ACTE_ID, OTHER_ID)
);

CREATE TABLE SKMST_ACTEPRODS (
    ACTEPROD_QTY  NUMBER(15),
    PRODUCT_ID    VARCHAR2(50) NOT NULL,
    ACTE_ID       VARCHAR2(15) NOT NULL
);

CREATE TABLE SKMST_ACTPARAMEDICS (
    PACT_ID        VARCHAR2(10) NOT NULL,
    PACT_DESC      VARCHAR2(100),
    PACT_PRICE     NUMBER(9),
    ACTIVE_STATUS  VARCHAR2(3),
    CONSTRAINT ACTPARAMEDICS_PK PRIMARY KEY (PACT_ID)
);

CREATE TABLE SKMST_ACTPAROTHERS (
    OTHER_ID    VARCHAR2(15) NOT NULL,
    PACT_ID     VARCHAR2(10) NOT NULL,
    ACTO_PRICE  NUMBER(15)
);

CREATE TABLE SKMST_ACTPARPRODUCTS (
    ACTPROD_QTY  NUMBER(15),
    PRODUCT_ID   VARCHAR2(50) NOT NULL,
    PACT_ID      VARCHAR2(15) NOT NULL
);

-- ---------- Modul: Wilayah ----------

CREATE TABLE SKMST_DESAS (
    DES_ID    NUMBER(10) NOT NULL,
    DES_NAME  VARCHAR2(50),
    KEC_ID    NUMBER(10) NOT NULL,
    CONSTRAINT DESAS_PK PRIMARY KEY (DES_ID)
);

CREATE TABLE SKMST_KABUPATENS (
    KAB_ID    NUMBER(10) NOT NULL,
    KAB_NAME  VARCHAR2(50),
    PROP_ID   NUMBER(10) NOT NULL,
    CONSTRAINT KABUPATENS_PK PRIMARY KEY (KAB_ID)
);

CREATE TABLE SKMST_KECAMATANS (
    KEC_ID    NUMBER(10) NOT NULL,
    KEC_NAME  VARCHAR2(50),
    KAB_ID    NUMBER(10) NOT NULL,
    CONSTRAINT KECAMATANS_PK PRIMARY KEY (KEC_ID)
);

CREATE TABLE SKMST_PROPINSIS (
    PROP_ID    NUMBER(10) NOT NULL,
    PROP_NAME  VARCHAR2(50),
    CONSTRAINT PROPINSIS_PK PRIMARY KEY (PROP_ID)
);

-- ---------- Modul: Terminologi SATUSEHAT ----------

CREATE TABLE SKMST_LOINC_CODES (
    LOINC_CODE   VARCHAR2(20) NOT NULL,
    DISPLAY      VARCHAR2(500) NOT NULL,
    DISPLAY_ID   VARCHAR2(500),
    COMPONENT    VARCHAR2(200),
    LOINC_CLASS  VARCHAR2(100),
    CREATED_AT   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT LOINC_CODES_PK PRIMARY KEY (LOINC_CODE)
);
COMMENT ON TABLE SKMST_LOINC_CODES IS 'Cache data LOINC untuk LOV pemeriksaan lab (Satu Sehat)';
COMMENT ON COLUMN SKMST_LOINC_CODES.LOINC_CODE IS 'Kode LOINC (contoh: 718-7)';
COMMENT ON COLUMN SKMST_LOINC_CODES.DISPLAY IS 'Nama resmi LOINC dalam bahasa Inggris';
COMMENT ON COLUMN SKMST_LOINC_CODES.DISPLAY_ID IS 'Nama Indonesia (diisi manual/admin)';
COMMENT ON COLUMN SKMST_LOINC_CODES.COMPONENT IS 'Komponen LOINC (contoh: Hemoglobin)';
COMMENT ON COLUMN SKMST_LOINC_CODES.LOINC_CLASS IS 'Kelas LOINC (contoh: HEM/BC, CHEM, UA)';

CREATE TABLE SKMST_SNOMED_CODES (
    SNOMED_CODE  VARCHAR2(20) NOT NULL,
    DISPLAY_EN   VARCHAR2(500) NOT NULL,
    DISPLAY_ID   VARCHAR2(500),
    VALUE_SET    VARCHAR2(50) DEFAULT 'condition-code' NOT NULL,
    CREATED_AT   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT SNOMED_CODES_PK PRIMARY KEY (SNOMED_CODE)
);
COMMENT ON TABLE SKMST_SNOMED_CODES IS 'Cache data SNOMED CT dari FHIR server untuk LOV keluhan utama, alergi, dll';
COMMENT ON COLUMN SKMST_SNOMED_CODES.SNOMED_CODE IS 'Kode SNOMED CT (contoh: 21522001)';
COMMENT ON COLUMN SKMST_SNOMED_CODES.DISPLAY_EN IS 'Nama Inggris dari FHIR server (otomatis)';
COMMENT ON COLUMN SKMST_SNOMED_CODES.DISPLAY_ID IS 'Nama Indonesia (diisi manual/admin)';
COMMENT ON COLUMN SKMST_SNOMED_CODES.VALUE_SET IS 'Jenis: condition-code, procedure-code, substance-code, dll';
COMMENT ON COLUMN SKMST_SNOMED_CODES.CREATED_AT IS 'Waktu pertama kali di-cache';

-- ---------- Modul: Akuntansi ----------

CREATE TABLE SKACC_ACCOUNTSES (
    ACC_DESC       VARCHAR2(100),
    ACC_ID         VARCHAR2(25) NOT NULL,
    ACTIVE_STATUS  VARCHAR2(3),
    KAS_STATUS     VARCHAR2(3),
    GRA_ID         VARCHAR2(25) NOT NULL,
    ACC_DK_STATUS  VARCHAR2(3),
    CONSTRAINT ACCOUNTSES_PK PRIMARY KEY (ACC_ID)
);

CREATE TABLE SKACC_CARABAYARS (
    ACTIVE_STATUS  VARCHAR2(3),
    CB_ID          VARCHAR2(25) NOT NULL,
    CB_DESC        VARCHAR2(100),
    ACC_ID         VARCHAR2(25),
    CONSTRAINT CARABAYARS_PK PRIMARY KEY (CB_ID)
);

CREATE TABLE SKACC_CONFACCTXNS (
    CONF_ID    VARCHAR2(240) NOT NULL,
    CONF_DESC  VARCHAR2(240),
    ACC_ID     VARCHAR2(25) NOT NULL,
    CONSTRAINT CONFACCTXNS_PK PRIMARY KEY (CONF_ID)
);

CREATE TABLE SKACC_GR_ACCOUNTSES (
    GRA_DESC    VARCHAR2(100),
    GRA_STATUS  VARCHAR2(5),
    GRA_ID      VARCHAR2(25) NOT NULL,
    DK_STATUS   VARCHAR2(5),
    CONSTRAINT GR_ACCOUNTSES_PK PRIMARY KEY (GRA_ID)
);

CREATE TABLE SKACC_TEMACCOUNTES (
    TEMACC_SEQ  NUMBER(5),
    ACC_ID      VARCHAR2(25) NOT NULL,
    TEMP_DTL    VARCHAR2(15) NOT NULL,
    CONSTRAINT TEMACCOUNTES_PK PRIMARY KEY (ACC_ID, TEMP_DTL)
);

CREATE TABLE SKACC_TEMLABARUGINERACADTLS (
    TEMP_DTL_DESC  VARCHAR2(100),
    TEMP_DTL       VARCHAR2(15) NOT NULL,
    TEMP_DTL_SEQ   NUMBER(15),
    TEMP_ID        VARCHAR2(25) NOT NULL,
    GRA_ID         VARCHAR2(25) NOT NULL,
    CONSTRAINT TEMLABARUGINERACADTLS_PK PRIMARY KEY (TEMP_DTL)
);

CREATE TABLE SKACC_TEMLABARUGINERACAHDRS (
    TEMP_STATUS  VARCHAR2(5),
    TEMP_ID      VARCHAR2(25) NOT NULL,
    TEMP_DESC    VARCHAR2(100),
    CONSTRAINT TEMLABARUGINERACAHDRS_PK PRIMARY KEY (TEMP_ID)
);

CREATE TABLE SKACC_TUCICOS (
    TUCICO_DESC    VARCHAR2(100),
    TUCICO_STATUS  VARCHAR2(3),
    TUCICO_ID      VARCHAR2(25) NOT NULL,
    ACTIVE_STATUS  VARCHAR2(3),
    ACC_ID         VARCHAR2(25) NOT NULL,
    CONSTRAINT TUCICOS_PK PRIMARY KEY (TUCICO_ID)
);

-- ---------- Modul: Kas & Hutang-Piutang ----------

CREATE TABLE SKTXN_CASHINDTLS (
    CASHIN_DTL  NUMBER(15) NOT NULL,
    CASHIN_NO   NUMBER(15) NOT NULL,
    SLS_NO      NUMBER(15) NOT NULL,
    CONSTRAINT CASHINDTLS_PK PRIMARY KEY (CASHIN_DTL)
);

CREATE TABLE SKTXN_CASHINHDRS (
    CASHIN_DATE   DATE,
    CASHIN_NO     NUMBER(15) NOT NULL,
    CASHIN_DESC   VARCHAR2(100),
    CASHIN_VALUE  NUMBER(15,2),
    KASIR_ID      VARCHAR2(25) NOT NULL,
    CM_ID         VARCHAR2(25) NOT NULL,
    CB_ID         VARCHAR2(25) NOT NULL,
    CONSTRAINT CASHINHDRS_PK PRIMARY KEY (CASHIN_NO)
);

CREATE TABLE SKTXN_CASHOUTDTLNONS (
    CASHOUT_DTL  NUMBER NOT NULL,
    CASHOUT_NO   NUMBER NOT NULL,
    RCV_NO       NUMBER NOT NULL,
    CONSTRAINT PK_TKTXN_CASHOUTDTLNONS PRIMARY KEY (CASHOUT_DTL)
);

CREATE TABLE SKTXN_CASHOUTDTLS (
    CASHOUT_DTL  NUMBER(15) NOT NULL,
    CASHOUT_NO   NUMBER(15) NOT NULL,
    RCV_NO       NUMBER(15) NOT NULL,
    CONSTRAINT CASHOUTDTLS_PK PRIMARY KEY (CASHOUT_DTL)
);

CREATE TABLE SKTXN_CASHOUTHDRNONS (
    CASHOUT_NO     NUMBER NOT NULL,
    CASHOUT_DATE   DATE NOT NULL,
    KASIR_ID       VARCHAR2(20),
    SUPP_ID        VARCHAR2(20),
    CB_ID          VARCHAR2(20),
    CASHOUT_DESC   VARCHAR2(400),
    CASHOUT_VALUE  NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT PK_TKTXN_CASHOUTHDRNONS PRIMARY KEY (CASHOUT_NO)
);

CREATE TABLE SKTXN_CASHOUTHDRS (
    CASHOUT_DATE   DATE,
    CASHOUT_NO     NUMBER(15) NOT NULL,
    CASHOUT_DESC   VARCHAR2(100),
    CASHOUT_VALUE  NUMBER(15,2),
    KASIR_ID       VARCHAR2(25) NOT NULL,
    SUPP_ID        VARCHAR2(25) NOT NULL,
    CB_ID          VARCHAR2(25) NOT NULL,
    CONSTRAINT CASHOUTHDRS_PK PRIMARY KEY (CASHOUT_NO)
);

CREATE TABLE SKTXN_SALDOAWALAKUNS (
    SA_ACC_K  NUMBER(15),
    SA_ACC_D  NUMBER(15),
    SA_YEAR   VARCHAR2(5) NOT NULL,
    ACC_ID    VARCHAR2(25) NOT NULL,
    CONSTRAINT SALDOAWALAKUNS_PK PRIMARY KEY (SA_YEAR, ACC_ID)
);

CREATE TABLE SKTXN_SALDOAWALHUTANGS (
    SAH_YEAR   VARCHAR2(5) NOT NULL,
    SAH_VALUE  NUMBER(15,2),
    SUPP_ID    VARCHAR2(25) NOT NULL,
    CONSTRAINT SALDOAWALHUTANGS_PK PRIMARY KEY (SAH_YEAR, SUPP_ID)
);

CREATE TABLE SKTXN_SALDOAWALPIUTANGS (
    SAP_VALUE  NUMBER(15,2),
    SAP_YEAR   VARCHAR2(5) NOT NULL,
    CM_ID      VARCHAR2(25) NOT NULL,
    CONSTRAINT SALDOAWALPIUTANGS_PK PRIMARY KEY (SAP_YEAR, CM_ID)
);

CREATE TABLE SKTXN_TUCASHINS (
    CI_DESC     VARCHAR2(100),
    CI_NOMINAL  NUMBER(15),
    CI_STATUS   VARCHAR2(3),
    CI_NO       NUMBER(15) NOT NULL,
    CI_DATE     DATE,
    TUCICO_ID   VARCHAR2(25) NOT NULL,
    KASIR_ID    VARCHAR2(25) NOT NULL,
    CB_ID       VARCHAR2(25) NOT NULL,
    CONSTRAINT TUCASHINS_PK PRIMARY KEY (CI_NO)
);

CREATE TABLE SKTXN_TUCASHOUTS (
    CO_DESC     VARCHAR2(100),
    CO_NOMINAL  NUMBER(15),
    CO_STATUS   VARCHAR2(3),
    CO_NO       NUMBER(15) NOT NULL,
    CO_DATE     DATE,
    TUCICO_ID   VARCHAR2(25) NOT NULL,
    KASIR_ID    VARCHAR2(25) NOT NULL,
    CB_ID       VARCHAR2(25) NOT NULL,
    CONSTRAINT TUCASHOUTS_PK PRIMARY KEY (CO_NO)
);

-- ---------- Modul: Apotek & Gudang (master) ----------

CREATE TABLE SKMST_CATEGORIES (
    CAT_DESC       VARCHAR2(100),
    ACTIVE_STATUS  VARCHAR2(3),
    CAT_ID         VARCHAR2(25) NOT NULL,
    CONSTRAINT CATEGORIES_PK PRIMARY KEY (CAT_ID)
);

CREATE TABLE SKMST_CONTENTS (
    CONT_ID    VARCHAR2(5) NOT NULL,
    CONT_DESC  VARCHAR2(50),
    CONSTRAINT CONTENTS_PK PRIMARY KEY (CONT_ID)
);

CREATE TABLE SKMST_CUSTOMERS (
    CM_NAME        VARCHAR2(100),
    CM_PHONE2      VARCHAR2(100),
    CM_ADDRESS     VARCHAR2(100),
    CM_PHONE1      VARCHAR2(100),
    CM_EMAIL       VARCHAR2(100),
    CM_ID          VARCHAR2(25) NOT NULL,
    ACTIVE_STATUS  VARCHAR2(3),
    KOTA_ID        VARCHAR2(15) NOT NULL,
    PROV_ID        VARCHAR2(15) NOT NULL,
    CONSTRAINT CUSTOMERS_PK PRIMARY KEY (CM_ID)
);

CREATE TABLE SKMST_EX_IMS (
    ID_EX       NUMBER(25) NOT NULL,
    EX_IM_NODE  VARCHAR2(4000),
    CONSTRAINT EX_IMS_PK PRIMARY KEY (ID_EX)
);

CREATE TABLE SKMST_KASIRS (
    ACTIVE_STATUS  VARCHAR2(3),
    KASIR_NAME     VARCHAR2(100),
    KASIR_ID       VARCHAR2(25) NOT NULL,
    CONSTRAINT KASIRS_PK PRIMARY KEY (KASIR_ID)
);

CREATE TABLE SKMST_KOTAS (
    KOTA_ID    VARCHAR2(15) NOT NULL,
    KOTA_NAME  VARCHAR2(100),
    PROV_ID    VARCHAR2(15) NOT NULL,
    CONSTRAINT KOTAS_PK PRIMARY KEY (KOTA_ID, PROV_ID)
);

CREATE TABLE SKMST_PRODUCTCONTENTS (
    PRC_DTL     NUMBER(5) NOT NULL,
    PRODUCT_ID  VARCHAR2(50),
    CONT_ID     VARCHAR2(5) NOT NULL,
    PRC_QTY     NUMBER(5,2),
    UOM_ID      VARCHAR2(10),
    CONSTRAINT PRODUCTCONTENTS_PK PRIMARY KEY (PRC_DTL)
);

CREATE TABLE SKMST_PRODUCTNONS (
    PRODUCT_ID     NUMBER NOT NULL,
    PRODUCT_NAME   VARCHAR2(150) NOT NULL,
    UOM_ID         VARCHAR2(20),
    COST_PRICE     NUMBER DEFAULT 0 NOT NULL,
    QTY_BOX        NUMBER DEFAULT 0 NOT NULL,
    LIMIT_STOCK    NUMBER DEFAULT 0,
    ACTIVE_STATUS  VARCHAR2(1) DEFAULT '1' NOT NULL,
    CONSTRAINT PK_TKMST_PRODUCTNONS PRIMARY KEY (PRODUCT_ID)
);
COMMENT ON TABLE SKMST_PRODUCTNONS IS 'Master barang non-medis (ATK/RT) ¿ stok tunggal di qty_box';
COMMENT ON COLUMN SKMST_PRODUCTNONS.QTY_BOX IS 'Stok berjalan ¿ di-update aplikasi saat posting/hapus penerimaan & opname';

CREATE TABLE SKMST_PRODUCTPAKETS (
    PAKET_DTL        NUMBER(15) NOT NULL,
    QTY              NUMBER(9,2),
    PRODUCT_ID       VARCHAR2(25) NOT NULL,
    PRODUCT_ID_PROD  VARCHAR2(25) NOT NULL,
    CONSTRAINT PRODUCTPAKETS_PK PRIMARY KEY (PAKET_DTL)
);

CREATE TABLE SKMST_PRODUCTS (
    MARGIN_PERSEN           NUMBER(9,2),
    SALES_PRICE             NUMBER(15,2),
    LIMIT_STOCK             NUMBER(15),
    QTY_BOX                 NUMBER(9,2),
    PRODUCT_RAK             VARCHAR2(100),
    PRODUCT_NAME            VARCHAR2(100),
    PRODUCT_TYPE            VARCHAR2(3),
    COST_PRICE              NUMBER(15,2),
    PRODUCT_ID              VARCHAR2(25) NOT NULL,
    CAT_ID                  VARCHAR2(25) NOT NULL,
    UOM_ID                  VARCHAR2(25) NOT NULL,
    SUPP_ID                 VARCHAR2(25) NOT NULL,
    ACTIVE_STATUS           VARCHAR2(3),
    "1_1"                   NUMBER(*,0),
    PRODUCT_ID_SATUSEHAT    VARCHAR2(50),
    PRODUCT_NAME_SATUSEHAT  VARCHAR2(250),
    CONSTRAINT PRODUCTS_PK PRIMARY KEY (PRODUCT_ID)
);
COMMENT ON COLUMN SKMST_PRODUCTS.PRODUCT_ID_SATUSEHAT IS 'Kode KFA SATUSEHAT (system http://sys-ids.kemkes.go.id/kfa) ¿ kosong = obat tidak bisa dikirim ke SATUSEHAT';
COMMENT ON COLUMN SKMST_PRODUCTS.PRODUCT_NAME_SATUSEHAT IS 'Nama resmi KFA SATUSEHAT ¿ dipakai sebagai display Medication.code; kosong = pakai product_name';

CREATE TABLE SKMST_PROVS (
    PROV_NAME  VARCHAR2(100),
    PROV_ID    VARCHAR2(15) NOT NULL,
    CONSTRAINT PROVS_PK PRIMARY KEY (PROV_ID)
);

CREATE TABLE SKMST_SIGNA_CATATANS (
    CATATAN        VARCHAR2(255) NOT NULL,
    ACTIVE_STATUS  VARCHAR2(1) DEFAULT '1' NOT NULL,
    CONSTRAINT PK_TKMST_SIGNA_CATATANS PRIMARY KEY (CATATAN)
);
COMMENT ON TABLE SKMST_SIGNA_CATATANS IS 'LOV catatan khusus signa e-resep rawat jalan';
COMMENT ON COLUMN SKMST_SIGNA_CATATANS.CATATAN IS 'Teks catatan khusus yang muncul di dropdown (PK)';
COMMENT ON COLUMN SKMST_SIGNA_CATATANS.ACTIVE_STATUS IS '1 = aktif, 0 = nonaktif';

CREATE TABLE SKMST_SUPPLIERS (
    ACTIVE_STATUS  VARCHAR2(3),
    SUPP_ID        VARCHAR2(25) NOT NULL,
    SUPP_NAME      VARCHAR2(100),
    SUPP_EMAIL     VARCHAR2(100),
    SUPP_PHONE1    VARCHAR2(15),
    SUPP_ADDRESS   VARCHAR2(250),
    SUPP_PHONE2    VARCHAR2(15),
    CONSTRAINT SUPPLIERS_PK PRIMARY KEY (SUPP_ID)
);

CREATE TABLE SKMST_UOMS (
    UOM_ID         VARCHAR2(25) NOT NULL,
    UOM_DESC       VARCHAR2(100),
    ACTIVE_STATUS  VARCHAR2(3),
    CONSTRAINT UOMS_PK PRIMARY KEY (UOM_ID)
);

-- ---------- Modul: Apotek & Gudang (transaksi) ----------

CREATE TABLE SKTXN_RCVDTLNONS (
    RCV_DTL      NUMBER NOT NULL,
    RCV_NO       NUMBER NOT NULL,
    PRODUCT_ID   NUMBER NOT NULL,
    QTY          NUMBER DEFAULT 0 NOT NULL,
    COST_PRICE   NUMBER DEFAULT 0 NOT NULL,
    DTL_DISKON   NUMBER DEFAULT 0,
    DTL_DISKON1  NUMBER DEFAULT 0,
    DTL_PERSEN   NUMBER DEFAULT 0,
    DTL_PERSEN1  NUMBER DEFAULT 0,
    CONSTRAINT PK_TKTXN_RCVDTLNONS PRIMARY KEY (RCV_DTL)
);

CREATE TABLE SKTXN_RCVDTLS (
    QTY          NUMBER(9,2),
    COST_PRICE   NUMBER(15,2),
    DTL_DISKON   NUMBER(9,2),
    RCV_DTL      NUMBER(15) NOT NULL,
    DTL_PERSEN   NUMBER(15,2),
    PRODUCT_ID   VARCHAR2(25) NOT NULL,
    RCV_NO       NUMBER(15) NOT NULL,
    DTL_DISKON1  NUMBER(15),
    DTL_PERSEN1  NUMBER(15,2),
    CONSTRAINT RCVDTLS_PK PRIMARY KEY (RCV_DTL)
);

CREATE TABLE SKTXN_RCVHDRNONS (
    RCV_NO          NUMBER NOT NULL,
    RCV_DATE        DATE NOT NULL,
    SUPP_ID         VARCHAR2(20),
    KASIR_ID        VARCHAR2(20),
    CB_ID           VARCHAR2(20),
    RCV_DESC        VARCHAR2(400),
    RCV_STATUS      VARCHAR2(1) DEFAULT 'A' NOT NULL,
    PAY_DATE        DATE,
    RCV_BAYAR       NUMBER DEFAULT 0,
    DUE_DATE        DATE,
    RCV_DISKON      NUMBER DEFAULT 0,
    RCV_PPN         NUMBER DEFAULT 0,
    RCV_PPN_STATUS  VARCHAR2(1) DEFAULT '0',
    RCV_MATERAI     NUMBER DEFAULT 0,
    CONSTRAINT PK_TKTXN_RCVHDRNONS PRIMARY KEY (RCV_NO)
);
COMMENT ON TABLE SKTXN_RCVHDRNONS IS 'Header penerimaan barang non-medis (rcv_no = MAX+1 per tabel ini; status H/L/F/A)';

CREATE TABLE SKTXN_RCVHDRS (
    PAY_DATE         DATE,
    CHECK_BOXSTATUS  VARCHAR2(3),
    RCV_DESC         VARCHAR2(100),
    RCV_STATUS       VARCHAR2(3),
    RCV_NO           NUMBER(15) NOT NULL,
    RCV_BAYAR        NUMBER(15,2),
    VCOUNT           NUMBER(15),
    DUE_DATE         DATE,
    RCV_DISKON       NUMBER(15,2),
    CB_ID            VARCHAR2(25),
    KASIR_ID         VARCHAR2(25) NOT NULL,
    SUPP_ID          VARCHAR2(25) NOT NULL,
    RCV_DATE         DATE,
    RCV_PPN          NUMBER(15,2),
    RCV_PPN_STATUS   VARCHAR2(3),
    RCV_MATERAI      NUMBER(15,2),
    CONSTRAINT RCVHDRS_PK PRIMARY KEY (RCV_NO)
);

CREATE TABLE SKTXN_RCVPAYMENTNONS (
    RCVP_NO     NUMBER NOT NULL,
    RCV_NO      NUMBER NOT NULL,
    RCVP_DATE   DATE NOT NULL,
    RCVP_VALUE  NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT PK_TKTXN_RCVPAYMENTNONS PRIMARY KEY (RCVP_NO)
);

CREATE TABLE SKTXN_RCVPAYMENTS (
    RCVP_DATE   DATE,
    RCVP_VALUE  NUMBER(15,2),
    RCVP_NO     NUMBER(15) NOT NULL,
    RCV_NO      NUMBER(15) NOT NULL,
    CONSTRAINT RCVPAYMENTS_PK PRIMARY KEY (RCVP_NO)
);

CREATE TABLE SKTXN_SALDOAWALSTOCKS (
    SA_YEAR      VARCHAR2(5) NOT NULL,
    SA_STOCKWH   NUMBER(15,2),
    PRODUCT_ID   VARCHAR2(25) NOT NULL,
    HPP_PRODUCT  NUMBER(15),
    CONSTRAINT SALDOAWALSTOCKS_PK PRIMARY KEY (SA_YEAR, PRODUCT_ID)
);

CREATE TABLE SKTXN_SALDOAWALSTOCKSNON (
    SA_YEAR     VARCHAR2(4) NOT NULL,
    PRODUCT_ID  NUMBER NOT NULL,
    SA_STOCKWH  NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT PK_TKTXN_SALDOAWALSTOCKSNON PRIMARY KEY (SA_YEAR, PRODUCT_ID)
);
COMMENT ON TABLE SKTXN_SALDOAWALSTOCKSNON IS 'Saldo awal stok barang non-medis per tahun (closing/input manual)';

CREATE TABLE SKTXN_SLSDTLS (
    QTY          NUMBER(9,2),
    SALES_PRICE  NUMBER(15,2),
    DTL_DISKON   NUMBER(9,2),
    SLS_DTL      NUMBER(15) NOT NULL,
    DTL_PERSEN   NUMBER(15,2),
    PRODUCT_ID   VARCHAR2(25) NOT NULL,
    SLS_NO       NUMBER(15) NOT NULL,
    CONSTRAINT SLSDTLS_PK PRIMARY KEY (SLS_DTL)
);

CREATE TABLE SKTXN_SLSHDRS (
    PAY_DATE         DATE,
    CHECK_BOXSTATUS  VARCHAR2(3),
    SLS_DESC         VARCHAR2(100),
    SLS_STATUS       VARCHAR2(3),
    SLS_NO           NUMBER(15) NOT NULL,
    SLS_BAYAR        NUMBER(15,2),
    VCOUNT           NUMBER(15),
    DUE_DATE         DATE,
    SLS_DISKON       NUMBER(15,2),
    CB_ID            VARCHAR2(25),
    KASIR_ID         VARCHAR2(25) NOT NULL,
    CM_ID            VARCHAR2(25) NOT NULL,
    SLS_DATE         DATE,
    CONSTRAINT SLSHDRS_PK PRIMARY KEY (SLS_NO)
);

CREATE TABLE SKTXN_SLSKIRIMS (
    SLS_PHONE     VARCHAR2(15),
    SLS_ADDRESS   VARCHAR2(1000),
    SLS_NO        NUMBER(15) NOT NULL,
    PROV_ID       VARCHAR2(15) NOT NULL,
    KOTA_ID       VARCHAR2(15) NOT NULL,
    SLS_NAME      VARCHAR2(100),
    SLS_RESI      VARCHAR2(100),
    SLS_EXPEDISI  VARCHAR2(100),
    CONSTRAINT SLSKIRIMS_PK PRIMARY KEY (SLS_NO)
);

CREATE TABLE SKTXN_SLSPAYMENTS (
    SLSP_DATE   DATE,
    SLSP_VALUE  NUMBER(15,2),
    SLSP_NO     NUMBER(15) NOT NULL,
    SLS_NO      NUMBER(15) NOT NULL,
    CONSTRAINT SLSPAYMENTS_PK PRIMARY KEY (SLSP_NO)
);

CREATE TABLE SKTXN_SOWHS (
    SO_NO       NUMBER NOT NULL,
    PRODUCT_ID  VARCHAR2(20) NOT NULL,
    SO_DATE     DATE DEFAULT SYSDATE,
    SO_D        NUMBER DEFAULT 0,
    SO_K        NUMBER DEFAULT 0,
    KASIR_ID    VARCHAR2(20),
    SO_DESC     VARCHAR2(100) DEFAULT 'SO',
    CONSTRAINT SOWHS_PK PRIMARY KEY (SO_NO)
);
COMMENT ON TABLE SKTXN_SOWHS IS 'Stock Opname Warehouse ??? catat selisih hasil opname per produk. INSERT-only.';
COMMENT ON COLUMN SKTXN_SOWHS.SO_NO IS 'PK auto-increment via NVL(MAX(so_no),0)+1 di app';
COMMENT ON COLUMN SKTXN_SOWHS.PRODUCT_ID IS 'FK ??? TKMST_PRODUCTS';
COMMENT ON COLUMN SKTXN_SOWHS.SO_DATE IS 'Tanggal opname (default SYSDATE)';
COMMENT ON COLUMN SKTXN_SOWHS.SO_D IS 'Debit/Masuk ??? fisik LEBIH dari catatan';
COMMENT ON COLUMN SKTXN_SOWHS.SO_K IS 'Kredit/Keluar ??? fisik KURANG dari catatan';
COMMENT ON COLUMN SKTXN_SOWHS.KASIR_ID IS 'FK ??? TKMST_KASIRS';
COMMENT ON COLUMN SKTXN_SOWHS.SO_DESC IS 'Default ''SO''';

CREATE TABLE SKTXN_SOWHSNON (
    SO_NO       NUMBER NOT NULL,
    PRODUCT_ID  NUMBER NOT NULL,
    SO_DATE     DATE NOT NULL,
    KASIR_ID    VARCHAR2(20),
    SO_DESC     VARCHAR2(100),
    SO_D        NUMBER DEFAULT 0 NOT NULL,
    SO_K        NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT PK_TKTXN_SOWHSNON PRIMARY KEY (SO_NO)
);
COMMENT ON TABLE SKTXN_SOWHSNON IS 'Stock opname non-medis ¿ selisih dicatat sbg mutasi SO; aplikasi ikut update qty_box';

-- ---------- Modul: Aplikasi & Identitas ----------

CREATE TABLE SKMST_APPLICATIONS (
    APP_CODE     VARCHAR2(25) NOT NULL,
    APP_SEQ      NUMBER(9),
    APP_TYPE     VARCHAR2(5),
    APP_DESC     VARCHAR2(50),
    APP_NAME     VARCHAR2(50),
    ITEM_SEQ     NUMBER(9),
    MODULE_CODE  VARCHAR2(25),
    CONSTRAINT APPLICATIONS_PK PRIMARY KEY (APP_CODE)
);

CREATE TABLE SKMST_IDENTITASES (
    INT_LOGO              VARCHAR2(240),
    INT_CITY              VARCHAR2(240),
    INT_PHONE1            VARCHAR2(240),
    INT_PHONE2            VARCHAR2(240),
    INT_ADDRESS           VARCHAR2(240),
    SERIAL_MACHINE        VARCHAR2(240),
    INT_FAX               VARCHAR2(240),
    INT_NAME              VARCHAR2(240) NOT NULL,
    APP_DESC              VARCHAR2(240),
    IMAGE_PATH            VARCHAR2(240),
    RCVUPDATE_COST_PRICE  VARCHAR2(1),
    QTY_WARNING           VARCHAR2(3),
    QTY_DUE_DATE          VARCHAR2(3),
    QTY_DUE_DATE_WARNING  VARCHAR2(3),
    DUE_DATE_WARNING      VARCHAR2(3),
    PRINT_DESC            VARCHAR2(1000),
    PRINT_STATUS          VARCHAR2(3),
    PLAFONT_SLS           VARCHAR2(3),
    PRINT_PDF_FOXIT_PATH  VARCHAR2(1000),
    BACKUP_DB             VARCHAR2(4000),
    SERIAL_NUMBER         VARCHAR2(4000),
    AUTO_PPN_STATUS       VARCHAR2(3),
    PPN_VALUE             NUMBER(15,2),
    LIMIT_STOCK           VARCHAR2(3),
    PRICE_PROFILE         VARCHAR2(100),
    ED_STATUS             VARCHAR2(3),
    CONSTRAINT IDENTITASES_PK PRIMARY KEY (INT_NAME)
);

CREATE TABLE SKMST_PARAMETERS (
    PAR_ID     NUMBER(5) NOT NULL,
    PAR_DESC   VARCHAR2(100),
    PAR_VALUE  NUMBER(9),
    CONSTRAINT PARAMETERS_PK PRIMARY KEY (PAR_ID)
);

CREATE TABLE SKMST_USERAPPLICATIONS (
    APP_CODE   VARCHAR2(25) NOT NULL,
    USER_CODE  VARCHAR2(50) NOT NULL,
    CONSTRAINT USERAPPLICATIONS_PK PRIMARY KEY (USER_CODE, APP_CODE)
);

CREATE TABLE SKMST_USERS (
    USER_LVL   VARCHAR2(25),
    USER_PSWD  VARCHAR2(50),
    USER_NAME  VARCHAR2(50),
    USER_CODE  VARCHAR2(50) NOT NULL,
    EMP_ID     VARCHAR2(15),
    CONSTRAINT USERS_PK PRIMARY KEY (USER_CODE)
);

-- ---------- Modul: BPJS & Log ----------

CREATE TABLE PASIEN (
    NIK            VARCHAR2(250),
    PATIENT_UUID   VARCHAR2(250),
    NAMA_PATIENT   VARCHAR2(250),
    JENIS_KELAMIN  VARCHAR2(250),
    TEMPAT_LAHIR   VARCHAR2(250),
    TGL_LAHIR      VARCHAR2(250),
    ALAMAT         VARCHAR2(250),
    DESA           VARCHAR2(250),
    KECAMATAN      VARCHAR2(250),
    KOTA           VARCHAR2(250),
    NOKARTU_BPJS   VARCHAR2(250)
);

CREATE TABLE REFERENSI_MOBILEJKN_BPJS (
    NOBOOKING         VARCHAR2(100),
    NO_RAWAT          VARCHAR2(100),
    NOMORKARTU        VARCHAR2(100),
    NIK               VARCHAR2(100),
    NOHP              VARCHAR2(100),
    KODEPOLI          VARCHAR2(100),
    PASIENBARU        VARCHAR2(100),
    NORM              VARCHAR2(100),
    TANGGALPERIKSA    VARCHAR2(100),
    KODEDOKTER        VARCHAR2(100),
    JAMPRAKTEK        VARCHAR2(100),
    JENISKUNJUNGAN    VARCHAR2(100),
    NOMORREFERENSI    VARCHAR2(100),
    NOMORANTREAN      VARCHAR2(100),
    ANGKAANTREAN      VARCHAR2(100),
    ESTIMASIDILAYANI  VARCHAR2(100),
    SISAKUOTAJKN      VARCHAR2(100),
    KUOTAJKN          VARCHAR2(100),
    SISAKUOTANONJKN   VARCHAR2(100),
    KUOTANONJKN       VARCHAR2(100),
    STATUS            VARCHAR2(100),
    VALIDASI          VARCHAR2(100),
    STATUSKIRIM       VARCHAR2(100),
    KETERANGAN_BATAL  VARCHAR2(1000),
    TANGGALBOOKING    VARCHAR2(100),
    DAFTARDARIAPP     VARCHAR2(100)
);

CREATE TABLE REF_BPJS_TABLE (
    REF_KETERANGAN  VARCHAR2(100) NOT NULL,
    REF_JSON        CLOB NOT NULL,
    CONSTRAINT REF_BPJS_TABLE_PK PRIMARY KEY (REF_KETERANGAN)
);

CREATE TABLE WEB_LOG_STATUS (
    ID                   NUMBER(25) NOT NULL,
    HTTP_REQ             VARCHAR2(2000),
    CODE                 VARCHAR2(50),
    DATE_REF             DATE,
    RESPONSE             CLOB,
    REQUESTTRANSFERTIME  VARCHAR2(100)
);

-- ---------- Modul: Sistem Laravel ----------

CREATE TABLE CACHE (
    KEY         VARCHAR2(255) NOT NULL,
    VALUE       CLOB NOT NULL,
    EXPIRATION  NUMBER(10) NOT NULL,
    CONSTRAINT PK_CACHE PRIMARY KEY (KEY)
);

CREATE TABLE CACHE_LOCKS (
    KEY         VARCHAR2(255) NOT NULL,
    OWNER       VARCHAR2(255) NOT NULL,
    EXPIRATION  NUMBER(10) NOT NULL,
    CONSTRAINT PK_CACHE_LOCKS PRIMARY KEY (KEY)
);

CREATE TABLE FAILED_JOBS (
    ID          NUMBER(19) NOT NULL,
    UUID        VARCHAR2(255) NOT NULL,
    CONNECTION  CLOB NOT NULL,
    QUEUE       CLOB NOT NULL,
    PAYLOAD     CLOB NOT NULL,
    EXCEPTION   CLOB NOT NULL,
    FAILED_AT   TIMESTAMP(6) NOT NULL,
    CONSTRAINT FAILED_JOBS_ID_PK PRIMARY KEY (ID),
    CONSTRAINT FAILED_JOBS_UUID_UK UNIQUE (UUID)
);

CREATE TABLE JOBS (
    ID            NUMBER(19) NOT NULL,
    QUEUE         VARCHAR2(255) NOT NULL,
    PAYLOAD       CLOB NOT NULL,
    ATTEMPTS      NUMBER(3) NOT NULL,
    RESERVED_AT   NUMBER(10),
    AVAILABLE_AT  NUMBER(10) NOT NULL,
    CREATED_AT    NUMBER(10) NOT NULL,
    CONSTRAINT PK_JOBS PRIMARY KEY (ID)
);

CREATE TABLE JOB_BATCHES (
    ID              VARCHAR2(255) NOT NULL,
    NAME            VARCHAR2(255) NOT NULL,
    TOTAL_JOBS      NUMBER(10) NOT NULL,
    PENDING_JOBS    NUMBER(10) NOT NULL,
    FAILED_JOBS     NUMBER(10) NOT NULL,
    FAILED_JOB_IDS  CLOB NOT NULL,
    OPTIONS         CLOB,
    CANCELLED_AT    NUMBER(10),
    CREATED_AT      NUMBER(10) NOT NULL,
    FINISHED_AT     NUMBER(10),
    CONSTRAINT PK_JOB_BATCHES PRIMARY KEY (ID)
);

CREATE TABLE MIGRATIONS (
    ID         NUMBER(10) NOT NULL,
    MIGRATION  VARCHAR2(255) NOT NULL,
    BATCH      NUMBER(10) NOT NULL,
    CONSTRAINT MIGRATIONS_ID_PK PRIMARY KEY (ID)
);

CREATE TABLE MODEL_HAS_PERMISSIONS (
    PERMISSION_ID  NUMBER(19) NOT NULL,
    MODEL_TYPE     VARCHAR2(255) NOT NULL,
    MODEL_ID       NUMBER(19) NOT NULL,
    CONSTRAINT MODEL_HAS_PERMX1PK PRIMARY KEY (PERMISSION_ID, MODEL_ID, MODEL_TYPE)
);

CREATE TABLE MODEL_HAS_ROLES (
    ROLE_ID     NUMBER(19) NOT NULL,
    MODEL_TYPE  VARCHAR2(255) NOT NULL,
    MODEL_ID    NUMBER(19) NOT NULL,
    CONSTRAINT MODEL_HAS_PERMX5 PRIMARY KEY (ROLE_ID, MODEL_ID, MODEL_TYPE)
);

CREATE TABLE PASSWORD_RESET_TOKENS (
    EMAIL       VARCHAR2(255) NOT NULL,
    TOKEN       VARCHAR2(255) NOT NULL,
    CREATED_AT  TIMESTAMP(6),
    CONSTRAINT PKSDF9213X PRIMARY KEY (EMAIL)
);

CREATE TABLE PERMISSIONS (
    ID          NUMBER(19) NOT NULL,
    NAME        VARCHAR2(255) NOT NULL,
    GUARD_NAME  VARCHAR2(255) NOT NULL,
    CREATED_AT  TIMESTAMP(6),
    UPDATED_AT  TIMESTAMP(6),
    CONSTRAINT PERMISSIONS_ID_PK PRIMARY KEY (ID),
    CONSTRAINT PERMISSIONS_NAME_GUARD_NAME_UK UNIQUE (NAME, GUARD_NAME)
);

CREATE TABLE PERSONAL_ACCESS_TOKENS (
    ID              NUMBER(19) NOT NULL,
    TOKENABLE_TYPE  VARCHAR2(255) NOT NULL,
    TOKENABLE_ID    NUMBER(19) NOT NULL,
    NAME            VARCHAR2(255) NOT NULL,
    TOKEN           VARCHAR2(64) NOT NULL,
    ABILITIES       CLOB,
    LAST_USED_AT    TIMESTAMP(6),
    EXPIRES_AT      TIMESTAMP(6),
    CREATED_AT      TIMESTAMP(6),
    UPDATED_AT      TIMESTAMP(6),
    CONSTRAINT PERSONAL_ACCESS_TOKENS_ID_PK PRIMARY KEY (ID),
    CONSTRAINT TOKENXW12PK UNIQUE (TOKEN)
);

CREATE TABLE ROLES (
    ID          NUMBER(19) NOT NULL,
    NAME        VARCHAR2(255) NOT NULL,
    GUARD_NAME  VARCHAR2(255) NOT NULL,
    CREATED_AT  TIMESTAMP(6),
    UPDATED_AT  TIMESTAMP(6),
    CONSTRAINT ROLES_ID_PK PRIMARY KEY (ID),
    CONSTRAINT ROLES_NAME_GUARD_NAME_UK UNIQUE (NAME, GUARD_NAME)
);

CREATE TABLE ROLE_HAS_PERMISSIONS (
    PERMISSION_ID  NUMBER(19) NOT NULL,
    ROLE_ID        NUMBER(19) NOT NULL,
    CONSTRAINT MODEL_HAS_PERMXOKD PRIMARY KEY (PERMISSION_ID, ROLE_ID)
);

CREATE TABLE SESSIONS (
    ID             VARCHAR2(255) NOT NULL,
    USER_ID        NUMBER(19),
    IP_ADDRESS     VARCHAR2(45),
    USER_AGENT     CLOB,
    PAYLOAD        CLOB NOT NULL,
    LAST_ACTIVITY  NUMBER(10) NOT NULL,
    CONSTRAINT PK_SESSIONS PRIMARY KEY (ID)
);

CREATE TABLE USERS (
    ID                 NUMBER(19) NOT NULL,
    NAME               VARCHAR2(255) NOT NULL,
    EMAIL              VARCHAR2(255) NOT NULL,
    EMAIL_VERIFIED_AT  TIMESTAMP(6),
    PASSWORD           VARCHAR2(255) NOT NULL,
    REMEMBER_TOKEN     VARCHAR2(100),
    CREATED_AT         TIMESTAMP(6),
    UPDATED_AT         TIMESTAMP(6),
    MYUSER_CODE        VARCHAR2(25),
    MYUSER_NAME        VARCHAR2(50),
    MYUSER_TTD_IMAGE   VARCHAR2(64),
    MYUSER_SIP         VARCHAR2(50),
    KASIR_ID           VARCHAR2(25),
    LAST_SEEN_AT       DATE,
    LAST_SEEN_ROUTE    VARCHAR2(150),
    CONSTRAINT USERS_ID_PK PRIMARY KEY (ID),
    CONSTRAINT USERS_EMAIL_UK UNIQUE (EMAIL)
);
COMMENT ON COLUMN USERS.KASIR_ID IS 'FK ke TKMST_KASIRS.kasir_id (mapping user Laravel ke kasir). Nullable.';
COMMENT ON COLUMN USERS.LAST_SEEN_AT IS 'Waktu aktivitas terakhir user (di-update middleware TrackUserActivity, throttle 1 menit)';
COMMENT ON COLUMN USERS.LAST_SEEN_ROUTE IS 'Route name halaman terakhir yang dilihat user';

-- ---------- Modul: Lain-lain ----------

CREATE TABLE INSTALL_TOKOKU (
    ID_EX       NUMBER(25) NOT NULL,
    EX_IM_NODE  VARCHAR2(4000)
);
