-- ============================================================
-- LANGKAH 2 — Foreign key antar tabel
-- Dibuat  : php artisan siklik:ddl-create  (2026-09-12 10:09)
-- Sumber  : data dictionary schema yang terhubung saat generate
-- Semua tabel dari 01 harus sudah ada. Urutan bebas karena FK ditambah setelah semua tabel dibuat.
-- ============================================================
SET DEFINE OFF
SET SQLBLANKLINES ON
SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

-- Foreign key (147)

-- MODEL_HAS_PERMISSIONS
ALTER TABLE MODEL_HAS_PERMISSIONS ADD CONSTRAINT MODEL_HAS_PERMX2 FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSIONS (ID) ON DELETE CASCADE;

-- MODEL_HAS_ROLES
ALTER TABLE MODEL_HAS_ROLES ADD CONSTRAINT MODEL_HAS_ROLES_ROLE_ID_FK FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE CASCADE;

-- ROLE_HAS_PERMISSIONS
ALTER TABLE ROLE_HAS_PERMISSIONS ADD CONSTRAINT MODEL_HAS_PERMX1S FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSIONS (ID) ON DELETE CASCADE;
ALTER TABLE ROLE_HAS_PERMISSIONS ADD CONSTRAINT MODEL_HAS_PERMX1SS FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE CASCADE;

-- SKACC_ACCOUNTSES
ALTER TABLE SKACC_ACCOUNTSES ADD CONSTRAINT ACCOUNTSES_GRA_FK FOREIGN KEY (GRA_ID) REFERENCES SKACC_GR_ACCOUNTSES (GRA_ID);

-- SKACC_CARABAYARS
ALTER TABLE SKACC_CARABAYARS ADD CONSTRAINT CARABAYARS_ACC_FK FOREIGN KEY (ACC_ID) REFERENCES SKACC_ACCOUNTSES (ACC_ID);

-- SKACC_CONFACCTXNS
ALTER TABLE SKACC_CONFACCTXNS ADD CONSTRAINT CONFACCTXNS_ACC_FK FOREIGN KEY (ACC_ID) REFERENCES SKACC_ACCOUNTSES (ACC_ID);

-- SKACC_TEMACCOUNTES
ALTER TABLE SKACC_TEMACCOUNTES ADD CONSTRAINT TEMACCOUNTES_ACC_FK FOREIGN KEY (ACC_ID) REFERENCES SKACC_ACCOUNTSES (ACC_ID);
ALTER TABLE SKACC_TEMACCOUNTES ADD CONSTRAINT TEMACCOUNTES_TEMP_DTL_FK FOREIGN KEY (TEMP_DTL) REFERENCES SKACC_TEMLABARUGINERACADTLS (TEMP_DTL);

-- SKACC_TEMLABARUGINERACADTLS
ALTER TABLE SKACC_TEMLABARUGINERACADTLS ADD CONSTRAINT TEMLABARUGINERACADTLS_GRA_FK FOREIGN KEY (GRA_ID) REFERENCES SKACC_GR_ACCOUNTSES (GRA_ID);
ALTER TABLE SKACC_TEMLABARUGINERACADTLS ADD CONSTRAINT TEMLABARUGINERACADTLS_TEMP_FK FOREIGN KEY (TEMP_ID) REFERENCES SKACC_TEMLABARUGINERACAHDRS (TEMP_ID);

-- SKACC_TUCICOS
ALTER TABLE SKACC_TUCICOS ADD CONSTRAINT TUCICOS_ACC_FK FOREIGN KEY (ACC_ID) REFERENCES SKACC_ACCOUNTSES (ACC_ID);

-- SKMST_ACCDOCOTHERS
ALTER TABLE SKMST_ACCDOCOTHERS ADD CONSTRAINT ACCDOCOTHERS_OTHER_FK FOREIGN KEY (OTHER_ID) REFERENCES SKMST_OTHERS (OTHER_ID);

-- SKMST_ACCDOCPRODUCTS
ALTER TABLE SKMST_ACCDOCPRODUCTS ADD CONSTRAINT ACCDOCPRODUCTS_ACCDOC_FK FOREIGN KEY (ACCDOC_ID) REFERENCES SKMST_ACCDOCS (ACCDOC_ID);

-- SKMST_ACTEOTHERS
ALTER TABLE SKMST_ACTEOTHERS ADD CONSTRAINT ACTEOTHERS_ACTE_FK FOREIGN KEY (ACTE_ID) REFERENCES SKMST_ACTEMPS (ACTE_ID);
ALTER TABLE SKMST_ACTEOTHERS ADD CONSTRAINT ACTEOTHERS_OTHER_FK FOREIGN KEY (OTHER_ID) REFERENCES SKMST_OTHERS (OTHER_ID);

-- SKMST_ACTEPRODS
ALTER TABLE SKMST_ACTEPRODS ADD CONSTRAINT ACTEPRODS_ACTE_FK FOREIGN KEY (ACTE_ID) REFERENCES SKMST_ACTEMPS (ACTE_ID);

-- SKMST_ACTPAROTHERS
ALTER TABLE SKMST_ACTPAROTHERS ADD CONSTRAINT ACTPAROTHERS_OTHER_FK FOREIGN KEY (OTHER_ID) REFERENCES SKMST_OTHERS (OTHER_ID);
ALTER TABLE SKMST_ACTPAROTHERS ADD CONSTRAINT ACTPAROTHERS_PACT_FK FOREIGN KEY (PACT_ID) REFERENCES SKMST_ACTPARAMEDICS (PACT_ID);

-- SKMST_ACTPARPRODUCTS
ALTER TABLE SKMST_ACTPARPRODUCTS ADD CONSTRAINT ACTPARPRODUCTS_PACT_FK FOREIGN KEY (PACT_ID) REFERENCES SKMST_ACTPARAMEDICS (PACT_ID);

-- SKMST_CLABITEMS
ALTER TABLE SKMST_CLABITEMS ADD CONSTRAINT CLABITEMS_CLAB_FK FOREIGN KEY (CLAB_ID) REFERENCES SKMST_CLABS (CLAB_ID);
ALTER TABLE SKMST_CLABITEMS ADD CONSTRAINT CLABITEMS_LOINC_CODE_FK FOREIGN KEY (LOINC_CODE) REFERENCES SKMST_LOINC_CODES (LOINC_CODE);

-- SKMST_CUSTOMERS
ALTER TABLE SKMST_CUSTOMERS ADD CONSTRAINT CUSTOMERS_KOTA_PROV_FK FOREIGN KEY (KOTA_ID, PROV_ID) REFERENCES SKMST_KOTAS (KOTA_ID, PROV_ID);
ALTER TABLE SKMST_CUSTOMERS ADD CONSTRAINT CUSTOMERS_PROV_FK FOREIGN KEY (PROV_ID) REFERENCES SKMST_PROVS (PROV_ID);

-- SKMST_DESAS
ALTER TABLE SKMST_DESAS ADD CONSTRAINT DESAS_KEC_FK FOREIGN KEY (KEC_ID) REFERENCES SKMST_KECAMATANS (KEC_ID);

-- SKMST_DOCTORS
ALTER TABLE SKMST_DOCTORS ADD CONSTRAINT DOCTORS_POLI_FK FOREIGN KEY (POLI_ID) REFERENCES SKMST_POLIS (POLI_ID);

-- SKMST_KABUPATENS
ALTER TABLE SKMST_KABUPATENS ADD CONSTRAINT KABUPATENS_PROP_FK FOREIGN KEY (PROP_ID) REFERENCES SKMST_PROPINSIS (PROP_ID);

-- SKMST_KECAMATANS
ALTER TABLE SKMST_KECAMATANS ADD CONSTRAINT KECAMATANS_KAB_FK FOREIGN KEY (KAB_ID) REFERENCES SKMST_KABUPATENS (KAB_ID);

-- SKMST_KOTAS
ALTER TABLE SKMST_KOTAS ADD CONSTRAINT KOTAS_PROV_FK FOREIGN KEY (PROV_ID) REFERENCES SKMST_PROVS (PROV_ID);

-- SKMST_PASIENS
ALTER TABLE SKMST_PASIENS ADD CONSTRAINT PASIENS_DES_FK FOREIGN KEY (DES_ID) REFERENCES SKMST_DESAS (DES_ID);
ALTER TABLE SKMST_PASIENS ADD CONSTRAINT PASIENS_EDU_FK FOREIGN KEY (EDU_ID) REFERENCES SKMST_EDUCATIONS (EDU_ID);
ALTER TABLE SKMST_PASIENS ADD CONSTRAINT PASIENS_JOB_FK FOREIGN KEY (JOB_ID) REFERENCES SKMST_JOBS (JOB_ID);
ALTER TABLE SKMST_PASIENS ADD CONSTRAINT PASIENS_KAB_FK FOREIGN KEY (KAB_ID) REFERENCES SKMST_KABUPATENS (KAB_ID);
ALTER TABLE SKMST_PASIENS ADD CONSTRAINT PASIENS_KEC_FK FOREIGN KEY (KEC_ID) REFERENCES SKMST_KECAMATANS (KEC_ID);
ALTER TABLE SKMST_PASIENS ADD CONSTRAINT PASIENS_PROP_FK FOREIGN KEY (PROP_ID) REFERENCES SKMST_PROPINSIS (PROP_ID);
ALTER TABLE SKMST_PASIENS ADD CONSTRAINT PASIENS_REL_FK FOREIGN KEY (REL_ID) REFERENCES SKMST_RELIGIONS (REL_ID);

-- SKMST_PRODUCTCONTENTS
ALTER TABLE SKMST_PRODUCTCONTENTS ADD CONSTRAINT PRODUCTCONTENTS_CONT_FK FOREIGN KEY (CONT_ID) REFERENCES SKMST_CONTENTS (CONT_ID);
ALTER TABLE SKMST_PRODUCTCONTENTS ADD CONSTRAINT PRODUCTCONTENTS_UOM_FK FOREIGN KEY (UOM_ID) REFERENCES SKMST_UOMS (UOM_ID);

-- SKMST_PRODUCTNONS
ALTER TABLE SKMST_PRODUCTNONS ADD CONSTRAINT PRODUCTNONS_UOM_FK FOREIGN KEY (UOM_ID) REFERENCES SKMST_UOMS (UOM_ID);

-- SKMST_PRODUCTPAKETS
ALTER TABLE SKMST_PRODUCTPAKETS ADD CONSTRAINT PRODUCTPAKETS_PRODUCT_FK FOREIGN KEY (PRODUCT_ID) REFERENCES SKMST_PRODUCTS (PRODUCT_ID);
ALTER TABLE SKMST_PRODUCTPAKETS ADD CONSTRAINT PRODUCTPAKE_PRODUCT_ID_PROD_FK FOREIGN KEY (PRODUCT_ID_PROD) REFERENCES SKMST_PRODUCTS (PRODUCT_ID);

-- SKMST_PRODUCTS
ALTER TABLE SKMST_PRODUCTS ADD CONSTRAINT PRODUCTS_CAT_FK FOREIGN KEY (CAT_ID) REFERENCES SKMST_CATEGORIES (CAT_ID);
ALTER TABLE SKMST_PRODUCTS ADD CONSTRAINT PRODUCTS_SUPP_FK FOREIGN KEY (SUPP_ID) REFERENCES SKMST_SUPPLIERS (SUPP_ID);
ALTER TABLE SKMST_PRODUCTS ADD CONSTRAINT PRODUCTS_UOM_FK FOREIGN KEY (UOM_ID) REFERENCES SKMST_UOMS (UOM_ID);

-- SKMST_RADIOLOGIS
ALTER TABLE SKMST_RADIOLOGIS ADD CONSTRAINT RADIOLOGIS_LOINC_CODE_FK FOREIGN KEY (LOINC_CODE) REFERENCES SKMST_LOINC_CODES (LOINC_CODE);

-- SKMST_SCPOLIS
ALTER TABLE SKMST_SCPOLIS ADD CONSTRAINT SCPOLIS_DAY_FK FOREIGN KEY (DAY_ID) REFERENCES SKMST_SCDAYS (DAY_ID);
ALTER TABLE SKMST_SCPOLIS ADD CONSTRAINT SCPOLIS_DR_FK FOREIGN KEY (DR_ID) REFERENCES SKMST_DOCTORS (DR_ID);
ALTER TABLE SKMST_SCPOLIS ADD CONSTRAINT SCPOLIS_POLI_FK FOREIGN KEY (POLI_ID) REFERENCES SKMST_POLIS (POLI_ID);

-- SKMST_USERAPPLICATIONS
ALTER TABLE SKMST_USERAPPLICATIONS ADD CONSTRAINT USERAPPLICATIONS_APP_CODE_FK FOREIGN KEY (APP_CODE) REFERENCES SKMST_APPLICATIONS (APP_CODE);
ALTER TABLE SKMST_USERAPPLICATIONS ADD CONSTRAINT USERAPPLICATIONS_USER_CODE_FK FOREIGN KEY (USER_CODE) REFERENCES SKMST_USERS (USER_CODE);

-- SKTXN_CASHINDTLS
ALTER TABLE SKTXN_CASHINDTLS ADD CONSTRAINT CASHINDTLS_CASHIN_NO_FK FOREIGN KEY (CASHIN_NO) REFERENCES SKTXN_CASHINHDRS (CASHIN_NO);
ALTER TABLE SKTXN_CASHINDTLS ADD CONSTRAINT CASHINDTLS_SLS_NO_FK FOREIGN KEY (SLS_NO) REFERENCES SKTXN_SLSHDRS (SLS_NO);

-- SKTXN_CASHINHDRS
ALTER TABLE SKTXN_CASHINHDRS ADD CONSTRAINT CASHINHDRS_CB_FK FOREIGN KEY (CB_ID) REFERENCES SKACC_CARABAYARS (CB_ID);
ALTER TABLE SKTXN_CASHINHDRS ADD CONSTRAINT CASHINHDRS_CM_FK FOREIGN KEY (CM_ID) REFERENCES SKMST_CUSTOMERS (CM_ID);
ALTER TABLE SKTXN_CASHINHDRS ADD CONSTRAINT CASHINHDRS_KASIR_FK FOREIGN KEY (KASIR_ID) REFERENCES SKMST_KASIRS (KASIR_ID);

-- SKTXN_CASHOUTDTLNONS
ALTER TABLE SKTXN_CASHOUTDTLNONS ADD CONSTRAINT FK_CODTLNONS_HDR FOREIGN KEY (CASHOUT_NO) REFERENCES SKTXN_CASHOUTHDRNONS (CASHOUT_NO);
ALTER TABLE SKTXN_CASHOUTDTLNONS ADD CONSTRAINT FK_CODTLNONS_RCV FOREIGN KEY (RCV_NO) REFERENCES SKTXN_RCVHDRNONS (RCV_NO);

-- SKTXN_CASHOUTDTLS
ALTER TABLE SKTXN_CASHOUTDTLS ADD CONSTRAINT CASHOUTDTLS_CASHOUT_NO_FK FOREIGN KEY (CASHOUT_NO) REFERENCES SKTXN_CASHOUTHDRS (CASHOUT_NO);
ALTER TABLE SKTXN_CASHOUTDTLS ADD CONSTRAINT CASHOUTDTLS_RCV_NO_FK FOREIGN KEY (RCV_NO) REFERENCES SKTXN_RCVHDRS (RCV_NO);

-- SKTXN_CASHOUTHDRNONS
ALTER TABLE SKTXN_CASHOUTHDRNONS ADD CONSTRAINT CASHOUTHDRNONS_CB_FK FOREIGN KEY (CB_ID) REFERENCES SKACC_CARABAYARS (CB_ID);
ALTER TABLE SKTXN_CASHOUTHDRNONS ADD CONSTRAINT CASHOUTHDRNONS_KASIR_FK FOREIGN KEY (KASIR_ID) REFERENCES SKMST_KASIRS (KASIR_ID);
ALTER TABLE SKTXN_CASHOUTHDRNONS ADD CONSTRAINT CASHOUTHDRNONS_SUPP_FK FOREIGN KEY (SUPP_ID) REFERENCES SKMST_SUPPLIERS (SUPP_ID);

-- SKTXN_CASHOUTHDRS
ALTER TABLE SKTXN_CASHOUTHDRS ADD CONSTRAINT CASHOUTHDRS_CB_FK FOREIGN KEY (CB_ID) REFERENCES SKACC_CARABAYARS (CB_ID);
ALTER TABLE SKTXN_CASHOUTHDRS ADD CONSTRAINT CASHOUTHDRS_KASIR_FK FOREIGN KEY (KASIR_ID) REFERENCES SKMST_KASIRS (KASIR_ID);
ALTER TABLE SKTXN_CASHOUTHDRS ADD CONSTRAINT CASHOUTHDRS_SUPP_FK FOREIGN KEY (SUPP_ID) REFERENCES SKMST_SUPPLIERS (SUPP_ID);

-- SKTXN_CHECKUPDTLS
ALTER TABLE SKTXN_CHECKUPDTLS ADD CONSTRAINT CHECKUPDTLS_CHECKUP_NO_FK FOREIGN KEY (CHECKUP_NO) REFERENCES SKTXN_CHECKUPHDRS (CHECKUP_NO);
ALTER TABLE SKTXN_CHECKUPDTLS ADD CONSTRAINT CHECKUPDTLS_CLABITEM_FK FOREIGN KEY (CLABITEM_ID) REFERENCES SKMST_CLABITEMS (CLABITEM_ID);

-- SKTXN_CHECKUPHDRS
ALTER TABLE SKTXN_CHECKUPHDRS ADD CONSTRAINT CHECKUPHDRS_DR_FK FOREIGN KEY (DR_ID) REFERENCES SKMST_DOCTORS (DR_ID);
ALTER TABLE SKTXN_CHECKUPHDRS ADD CONSTRAINT CHECKUPHDRS_KASIR_FK FOREIGN KEY (KASIR_ID) REFERENCES SKMST_KASIRS (KASIR_ID);
ALTER TABLE SKTXN_CHECKUPHDRS ADD CONSTRAINT CHECKUPHDRS_REG_NO_FK FOREIGN KEY (REG_NO) REFERENCES SKMST_PASIENS (REG_NO);

-- SKTXN_CHECKUPOBATS
ALTER TABLE SKTXN_CHECKUPOBATS ADD CONSTRAINT CHECKUPOBATS_CHECKUP_NO_FK FOREIGN KEY (CHECKUP_NO) REFERENCES SKTXN_CHECKUPHDRS (CHECKUP_NO);
ALTER TABLE SKTXN_CHECKUPOBATS ADD CONSTRAINT CHECKUPOBATS_PRODUCT_FK FOREIGN KEY (PRODUCT_ID) REFERENCES SKMST_PRODUCTS (PRODUCT_ID);

-- SKTXN_CHECKUPOUTDTLS
ALTER TABLE SKTXN_CHECKUPOUTDTLS ADD CONSTRAINT CHECKUPOUTDTLS_CHECKUP_NO_FK FOREIGN KEY (CHECKUP_NO) REFERENCES SKTXN_CHECKUPHDRS (CHECKUP_NO);

-- SKTXN_RCVDTLNONS
ALTER TABLE SKTXN_RCVDTLNONS ADD CONSTRAINT FK_RCVDTLNONS_HDR FOREIGN KEY (RCV_NO) REFERENCES SKTXN_RCVHDRNONS (RCV_NO);
ALTER TABLE SKTXN_RCVDTLNONS ADD CONSTRAINT FK_RCVDTLNONS_PRD FOREIGN KEY (PRODUCT_ID) REFERENCES SKMST_PRODUCTNONS (PRODUCT_ID);

-- SKTXN_RCVDTLS
ALTER TABLE SKTXN_RCVDTLS ADD CONSTRAINT RCVDTLS_PRODUCT_FK FOREIGN KEY (PRODUCT_ID) REFERENCES SKMST_PRODUCTS (PRODUCT_ID);
ALTER TABLE SKTXN_RCVDTLS ADD CONSTRAINT RCVDTLS_RCV_NO_FK FOREIGN KEY (RCV_NO) REFERENCES SKTXN_RCVHDRS (RCV_NO);

-- SKTXN_RCVHDRNONS
ALTER TABLE SKTXN_RCVHDRNONS ADD CONSTRAINT RCVHDRNONS_CB_FK FOREIGN KEY (CB_ID) REFERENCES SKACC_CARABAYARS (CB_ID);
ALTER TABLE SKTXN_RCVHDRNONS ADD CONSTRAINT RCVHDRNONS_KASIR_FK FOREIGN KEY (KASIR_ID) REFERENCES SKMST_KASIRS (KASIR_ID);
ALTER TABLE SKTXN_RCVHDRNONS ADD CONSTRAINT RCVHDRNONS_SUPP_FK FOREIGN KEY (SUPP_ID) REFERENCES SKMST_SUPPLIERS (SUPP_ID);

-- SKTXN_RCVHDRS
ALTER TABLE SKTXN_RCVHDRS ADD CONSTRAINT RCVHDRS_CB_FK FOREIGN KEY (CB_ID) REFERENCES SKACC_CARABAYARS (CB_ID);
ALTER TABLE SKTXN_RCVHDRS ADD CONSTRAINT RCVHDRS_KASIR_FK FOREIGN KEY (KASIR_ID) REFERENCES SKMST_KASIRS (KASIR_ID);
ALTER TABLE SKTXN_RCVHDRS ADD CONSTRAINT RCVHDRS_SUPP_FK FOREIGN KEY (SUPP_ID) REFERENCES SKMST_SUPPLIERS (SUPP_ID);

-- SKTXN_RCVPAYMENTNONS
ALTER TABLE SKTXN_RCVPAYMENTNONS ADD CONSTRAINT FK_RCVPAYNONS_HDR FOREIGN KEY (RCV_NO) REFERENCES SKTXN_RCVHDRNONS (RCV_NO);

-- SKTXN_RCVPAYMENTS
ALTER TABLE SKTXN_RCVPAYMENTS ADD CONSTRAINT RCVPAYMENTS_RCV_NO_FK FOREIGN KEY (RCV_NO) REFERENCES SKTXN_RCVHDRS (RCV_NO);

-- SKTXN_RJACCDOCS
ALTER TABLE SKTXN_RJACCDOCS ADD CONSTRAINT RJACCDOCS_ACCDOC_FK FOREIGN KEY (ACCDOC_ID) REFERENCES SKMST_ACCDOCS (ACCDOC_ID);
ALTER TABLE SKTXN_RJACCDOCS ADD CONSTRAINT RJACCDOCS_DR_FK FOREIGN KEY (DR_ID) REFERENCES SKMST_DOCTORS (DR_ID);
ALTER TABLE SKTXN_RJACCDOCS ADD CONSTRAINT RJACCDOCS_RJ_NO_FK FOREIGN KEY (RJ_NO) REFERENCES SKTXN_RJHDRS (RJ_NO);

-- SKTXN_RJACTEMPS
ALTER TABLE SKTXN_RJACTEMPS ADD CONSTRAINT RJACTEMPS_ACTE_FK FOREIGN KEY (ACTE_ID) REFERENCES SKMST_ACTEMPS (ACTE_ID);
ALTER TABLE SKTXN_RJACTEMPS ADD CONSTRAINT RJACTEMPS_RJ_NO_FK FOREIGN KEY (RJ_NO) REFERENCES SKTXN_RJHDRS (RJ_NO);

-- SKTXN_RJACTPARAMS
ALTER TABLE SKTXN_RJACTPARAMS ADD CONSTRAINT RJACTPARAMS_PACT_FK FOREIGN KEY (PACT_ID) REFERENCES SKMST_ACTPARAMEDICS (PACT_ID);
ALTER TABLE SKTXN_RJACTPARAMS ADD CONSTRAINT RJACTPARAMS_RJ_NO_FK FOREIGN KEY (RJ_NO) REFERENCES SKTXN_RJHDRS (RJ_NO);

-- SKTXN_RJCASHINS
ALTER TABLE SKTXN_RJCASHINS ADD CONSTRAINT RJCASHINS_CB_FK FOREIGN KEY (CB_ID) REFERENCES SKACC_CARABAYARS (CB_ID);
ALTER TABLE SKTXN_RJCASHINS ADD CONSTRAINT RJCASHINS_KASIR_FK FOREIGN KEY (KASIR_ID) REFERENCES SKMST_KASIRS (KASIR_ID);
ALTER TABLE SKTXN_RJCASHINS ADD CONSTRAINT RJCASHINS_RJ_NO_FK FOREIGN KEY (RJ_NO) REFERENCES SKTXN_RJHDRS (RJ_NO);

-- SKTXN_RJDTLS
ALTER TABLE SKTXN_RJDTLS ADD CONSTRAINT RJDTLS_DIAG_FK FOREIGN KEY (DIAG_ID) REFERENCES SKMST_MSTDIAGS (DIAG_ID);
ALTER TABLE SKTXN_RJDTLS ADD CONSTRAINT RJDTLS_RJ_NO_FK FOREIGN KEY (RJ_NO) REFERENCES SKTXN_RJHDRS (RJ_NO);

-- SKTXN_RJHDRS
ALTER TABLE SKTXN_RJHDRS ADD CONSTRAINT RJHDRS_CB_FK FOREIGN KEY (CB_ID) REFERENCES SKACC_CARABAYARS (CB_ID);
ALTER TABLE SKTXN_RJHDRS ADD CONSTRAINT RJHDRS_DR_FK FOREIGN KEY (DR_ID) REFERENCES SKMST_DOCTORS (DR_ID);
ALTER TABLE SKTXN_RJHDRS ADD CONSTRAINT RJHDRS_KASIR_FK FOREIGN KEY (KASIR_ID) REFERENCES SKMST_KASIRS (KASIR_ID);
ALTER TABLE SKTXN_RJHDRS ADD CONSTRAINT RJHDRS_KLAIM_FK FOREIGN KEY (KLAIM_ID) REFERENCES SKMST_KLAIMTYPES (KLAIM_ID);
ALTER TABLE SKTXN_RJHDRS ADD CONSTRAINT RJHDRS_POLI_FK FOREIGN KEY (POLI_ID) REFERENCES SKMST_POLIS (POLI_ID);
ALTER TABLE SKTXN_RJHDRS ADD CONSTRAINT RJHDRS_REG_NO_FK FOREIGN KEY (REG_NO) REFERENCES SKMST_PASIENS (REG_NO);

-- SKTXN_RJLABS
ALTER TABLE SKTXN_RJLABS ADD CONSTRAINT RJLABS_CHECKUP_NO_FK FOREIGN KEY (CHECKUP_NO) REFERENCES SKTXN_CHECKUPHDRS (CHECKUP_NO);
ALTER TABLE SKTXN_RJLABS ADD CONSTRAINT RJLABS_RJ_NO_FK FOREIGN KEY (RJ_NO) REFERENCES SKTXN_RJHDRS (RJ_NO);

-- SKTXN_RJOBATRACIKANS
ALTER TABLE SKTXN_RJOBATRACIKANS ADD CONSTRAINT RJOBATRACIKANS_ACTE_DTL_FK FOREIGN KEY (ACTE_DTL) REFERENCES SKTXN_RJACTEMPS (ACTE_DTL);
ALTER TABLE SKTXN_RJOBATRACIKANS ADD CONSTRAINT RJOBATRACIKANS_PACT_DTL_FK FOREIGN KEY (PACT_DTL) REFERENCES SKTXN_RJACTPARAMS (PACT_DTL);
ALTER TABLE SKTXN_RJOBATRACIKANS ADD CONSTRAINT RJOBATRACIKANS_RJHN_DTL_FK FOREIGN KEY (RJHN_DTL) REFERENCES SKTXN_RJACCDOCS (RJHN_DTL);
ALTER TABLE SKTXN_RJOBATRACIKANS ADD CONSTRAINT RJOBATRACIKANS_RJOBAT_DTL_FK FOREIGN KEY (RJOBAT_DTL) REFERENCES SKTXN_RJOBATS (RJOBAT_DTL);
ALTER TABLE SKTXN_RJOBATRACIKANS ADD CONSTRAINT RJOBATRACIKANS_RJ_NO_FK FOREIGN KEY (RJ_NO) REFERENCES SKTXN_RJHDRS (RJ_NO);

-- SKTXN_RJOBATS
ALTER TABLE SKTXN_RJOBATS ADD CONSTRAINT RJOBATS_ACTE_DTL_FK FOREIGN KEY (ACTE_DTL) REFERENCES SKTXN_RJACTEMPS (ACTE_DTL);
ALTER TABLE SKTXN_RJOBATS ADD CONSTRAINT RJOBATS_PACT_DTL_FK FOREIGN KEY (PACT_DTL) REFERENCES SKTXN_RJACTPARAMS (PACT_DTL);
ALTER TABLE SKTXN_RJOBATS ADD CONSTRAINT RJOBATS_PRODUCT_FK FOREIGN KEY (PRODUCT_ID) REFERENCES SKMST_PRODUCTS (PRODUCT_ID);
ALTER TABLE SKTXN_RJOBATS ADD CONSTRAINT RJOBATS_RJHN_DTL_FK FOREIGN KEY (RJHN_DTL) REFERENCES SKTXN_RJACCDOCS (RJHN_DTL);
ALTER TABLE SKTXN_RJOBATS ADD CONSTRAINT RJOBATS_RJ_NO_FK FOREIGN KEY (RJ_NO) REFERENCES SKTXN_RJHDRS (RJ_NO);

-- SKTXN_RJOTHERS
ALTER TABLE SKTXN_RJOTHERS ADD CONSTRAINT RJOTHERS_ACTE_DTL_FK FOREIGN KEY (ACTE_DTL) REFERENCES SKTXN_RJACTEMPS (ACTE_DTL);
ALTER TABLE SKTXN_RJOTHERS ADD CONSTRAINT RJOTHERS_OTHER_FK FOREIGN KEY (OTHER_ID) REFERENCES SKMST_OTHERS (OTHER_ID);
ALTER TABLE SKTXN_RJOTHERS ADD CONSTRAINT RJOTHERS_PACT_DTL_FK FOREIGN KEY (PACT_DTL) REFERENCES SKTXN_RJACTPARAMS (PACT_DTL);
ALTER TABLE SKTXN_RJOTHERS ADD CONSTRAINT RJOTHERS_RJHN_DTL_FK FOREIGN KEY (RJHN_DTL) REFERENCES SKTXN_RJACCDOCS (RJHN_DTL);
ALTER TABLE SKTXN_RJOTHERS ADD CONSTRAINT RJOTHERS_RJ_NO_FK FOREIGN KEY (RJ_NO) REFERENCES SKTXN_RJHDRS (RJ_NO);

-- SKTXN_RJRADS
ALTER TABLE SKTXN_RJRADS ADD CONSTRAINT RJRADS_RAD_FK FOREIGN KEY (RAD_ID) REFERENCES SKMST_RADIOLOGIS (RAD_ID);
ALTER TABLE SKTXN_RJRADS ADD CONSTRAINT RJRADS_RJ_NO_FK FOREIGN KEY (RJ_NO) REFERENCES SKTXN_RJHDRS (RJ_NO);

-- SKTXN_RJUPLOADBPJSES
ALTER TABLE SKTXN_RJUPLOADBPJSES ADD CONSTRAINT RJUPLOADBPJSES_RJ_NO_FK FOREIGN KEY (RJ_NO) REFERENCES SKTXN_RJHDRS (RJ_NO);

-- SKTXN_SALDOAWALAKUNS
ALTER TABLE SKTXN_SALDOAWALAKUNS ADD CONSTRAINT SALDOAWALAKUNS_ACC_FK FOREIGN KEY (ACC_ID) REFERENCES SKACC_ACCOUNTSES (ACC_ID);

-- SKTXN_SALDOAWALHUTANGS
ALTER TABLE SKTXN_SALDOAWALHUTANGS ADD CONSTRAINT SALDOAWALHUTANGS_SUPP_FK FOREIGN KEY (SUPP_ID) REFERENCES SKMST_SUPPLIERS (SUPP_ID);

-- SKTXN_SALDOAWALPIUTANGS
ALTER TABLE SKTXN_SALDOAWALPIUTANGS ADD CONSTRAINT SALDOAWALPIUTANGS_CM_FK FOREIGN KEY (CM_ID) REFERENCES SKMST_CUSTOMERS (CM_ID);

-- SKTXN_SALDOAWALSTOCKS
ALTER TABLE SKTXN_SALDOAWALSTOCKS ADD CONSTRAINT SALDOAWALSTOCKS_PRODUCT_FK FOREIGN KEY (PRODUCT_ID) REFERENCES SKMST_PRODUCTS (PRODUCT_ID);

-- SKTXN_SALDOAWALSTOCKSNON
ALTER TABLE SKTXN_SALDOAWALSTOCKSNON ADD CONSTRAINT FK_SALDONON_PRD FOREIGN KEY (PRODUCT_ID) REFERENCES SKMST_PRODUCTNONS (PRODUCT_ID);

-- SKTXN_SLSDTLS
ALTER TABLE SKTXN_SLSDTLS ADD CONSTRAINT SLSDTLS_PRODUCT_FK FOREIGN KEY (PRODUCT_ID) REFERENCES SKMST_PRODUCTS (PRODUCT_ID);
ALTER TABLE SKTXN_SLSDTLS ADD CONSTRAINT SLSDTLS_SLS_NO_FK FOREIGN KEY (SLS_NO) REFERENCES SKTXN_SLSHDRS (SLS_NO);

-- SKTXN_SLSHDRS
ALTER TABLE SKTXN_SLSHDRS ADD CONSTRAINT SLSHDRS_CB_FK FOREIGN KEY (CB_ID) REFERENCES SKACC_CARABAYARS (CB_ID);
ALTER TABLE SKTXN_SLSHDRS ADD CONSTRAINT SLSHDRS_CM_FK FOREIGN KEY (CM_ID) REFERENCES SKMST_CUSTOMERS (CM_ID);
ALTER TABLE SKTXN_SLSHDRS ADD CONSTRAINT SLSHDRS_KASIR_FK FOREIGN KEY (KASIR_ID) REFERENCES SKMST_KASIRS (KASIR_ID);

-- SKTXN_SLSKIRIMS
ALTER TABLE SKTXN_SLSKIRIMS ADD CONSTRAINT SLSKIRIMS_KOTA_PROV_FK FOREIGN KEY (KOTA_ID, PROV_ID) REFERENCES SKMST_KOTAS (KOTA_ID, PROV_ID);
ALTER TABLE SKTXN_SLSKIRIMS ADD CONSTRAINT SLSKIRIMS_PROV_FK FOREIGN KEY (PROV_ID) REFERENCES SKMST_PROVS (PROV_ID);
ALTER TABLE SKTXN_SLSKIRIMS ADD CONSTRAINT SLSKIRIMS_SLS_NO_FK FOREIGN KEY (SLS_NO) REFERENCES SKTXN_SLSHDRS (SLS_NO);

-- SKTXN_SLSPAYMENTS
ALTER TABLE SKTXN_SLSPAYMENTS ADD CONSTRAINT SLSPAYMENTS_SLS_NO_FK FOREIGN KEY (SLS_NO) REFERENCES SKTXN_SLSHDRS (SLS_NO);

-- SKTXN_SOWHS
ALTER TABLE SKTXN_SOWHS ADD CONSTRAINT SOWHS_KASIR_FK FOREIGN KEY (KASIR_ID) REFERENCES SKMST_KASIRS (KASIR_ID);
ALTER TABLE SKTXN_SOWHS ADD CONSTRAINT SOWHS_PRODUCT_FK FOREIGN KEY (PRODUCT_ID) REFERENCES SKMST_PRODUCTS (PRODUCT_ID);

-- SKTXN_SOWHSNON
ALTER TABLE SKTXN_SOWHSNON ADD CONSTRAINT FK_SOWHSNON_PRD FOREIGN KEY (PRODUCT_ID) REFERENCES SKMST_PRODUCTNONS (PRODUCT_ID);
ALTER TABLE SKTXN_SOWHSNON ADD CONSTRAINT SOWHSNON_KASIR_FK FOREIGN KEY (KASIR_ID) REFERENCES SKMST_KASIRS (KASIR_ID);

-- SKTXN_TUCASHINS
ALTER TABLE SKTXN_TUCASHINS ADD CONSTRAINT TUCASHINS_CB_FK FOREIGN KEY (CB_ID) REFERENCES SKACC_CARABAYARS (CB_ID);
ALTER TABLE SKTXN_TUCASHINS ADD CONSTRAINT TUCASHINS_KASIR_FK FOREIGN KEY (KASIR_ID) REFERENCES SKMST_KASIRS (KASIR_ID);
ALTER TABLE SKTXN_TUCASHINS ADD CONSTRAINT TUCASHINS_TUCICO_FK FOREIGN KEY (TUCICO_ID) REFERENCES SKACC_TUCICOS (TUCICO_ID);

-- SKTXN_TUCASHOUTS
ALTER TABLE SKTXN_TUCASHOUTS ADD CONSTRAINT TUCASHOUTS_CB_FK FOREIGN KEY (CB_ID) REFERENCES SKACC_CARABAYARS (CB_ID);
ALTER TABLE SKTXN_TUCASHOUTS ADD CONSTRAINT TUCASHOUTS_KASIR_FK FOREIGN KEY (KASIR_ID) REFERENCES SKMST_KASIRS (KASIR_ID);
ALTER TABLE SKTXN_TUCASHOUTS ADD CONSTRAINT TUCASHOUTS_TUCICO_FK FOREIGN KEY (TUCICO_ID) REFERENCES SKACC_TUCICOS (TUCICO_ID);
