-- ============================================================
-- LANGKAH 3 — Index lepas (bukan pendukung PK/UK)
-- Dibuat  : php artisan siklik:ddl-create  (2026-09-12 10:09)
-- Sumber  : data dictionary schema yang terhubung saat generate
-- Termasuk index fungsi UPPER(...) untuk pencarian LOINC/SNOMED.
-- ============================================================
SET DEFINE OFF
SET SQLBLANKLINES ON
SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

-- Index lepas (161)

-- JOBS
CREATE INDEX IDX_JOBS_QUEUE ON JOBS (QUEUE);

-- MODEL_HAS_PERMISSIONS
CREATE INDEX MODEL_HAS_PERMX1 ON MODEL_HAS_PERMISSIONS (MODEL_ID, MODEL_TYPE);

-- MODEL_HAS_ROLES
CREATE INDEX MODEL_HAS_PERMXIX ON MODEL_HAS_ROLES (MODEL_ID, MODEL_TYPE);

-- PERSONAL_ACCESS_TOKENS
CREATE INDEX TOKENXW12PK1 ON PERSONAL_ACCESS_TOKENS (TOKENABLE_TYPE, TOKENABLE_ID);

-- SESSIONS
CREATE INDEX IDX_SESSIONS_LAST_ACTIVITY ON SESSIONS (LAST_ACTIVITY);
CREATE INDEX IDX_SESSIONS_USER_ID ON SESSIONS (USER_ID);

-- SKACC_ACCOUNTSES
CREATE INDEX ACCOUNTSES_GRA_IX ON SKACC_ACCOUNTSES (GRA_ID);

-- SKACC_CARABAYARS
CREATE INDEX CARABAYARS_ACC_IX ON SKACC_CARABAYARS (ACC_ID);

-- SKACC_CONFACCTXNS
CREATE INDEX CONFACCTXNS_ACC_IX ON SKACC_CONFACCTXNS (ACC_ID);

-- SKACC_TEMACCOUNTES
CREATE INDEX TEMACCOUNTES_ACC_IX ON SKACC_TEMACCOUNTES (ACC_ID);
CREATE INDEX TEMACCOUNTES_TEMP_DTL_IX ON SKACC_TEMACCOUNTES (TEMP_DTL);

-- SKACC_TEMLABARUGINERACADTLS
CREATE INDEX TEMLABARUGINERACADTLS_GRA_IX ON SKACC_TEMLABARUGINERACADTLS (GRA_ID);
CREATE INDEX TEMLABARUGINERACADTLS_TEMP_IX ON SKACC_TEMLABARUGINERACADTLS (TEMP_ID);

-- SKACC_TUCICOS
CREATE INDEX TUCICOS_ACC_IX ON SKACC_TUCICOS (ACC_ID);

-- SKMST_ACCDOCOTHERS
CREATE INDEX ACCDOCOTHERS_OTHER_IX ON SKMST_ACCDOCOTHERS (OTHER_ID);

-- SKMST_ACCDOCPRODUCTS
CREATE INDEX ACCDOCPRODUCTS_ACCDOC_IX ON SKMST_ACCDOCPRODUCTS (ACCDOC_ID);

-- SKMST_ACTEOTHERS
CREATE INDEX ACTEOTHERS_ACTE_IX ON SKMST_ACTEOTHERS (ACTE_ID);
CREATE INDEX ACTEOTHERS_OTHER_IX ON SKMST_ACTEOTHERS (OTHER_ID);

-- SKMST_ACTEPRODS
CREATE INDEX ACTEPRODS_ACTE_IX ON SKMST_ACTEPRODS (ACTE_ID);

-- SKMST_ACTPAROTHERS
CREATE INDEX ACTPAROTHERS_OTHER_IX ON SKMST_ACTPAROTHERS (OTHER_ID);
CREATE INDEX ACTPAROTHERS_PACT_IX ON SKMST_ACTPAROTHERS (PACT_ID);

-- SKMST_ACTPARPRODUCTS
CREATE INDEX ACTPARPRODUCTS_PACT_IX ON SKMST_ACTPARPRODUCTS (PACT_ID);

-- SKMST_CLABITEMS
CREATE INDEX CLABITEMS_CLAB_IX ON SKMST_CLABITEMS (CLAB_ID);
CREATE INDEX CLABITEMS_LOINC_CODE_IX ON SKMST_CLABITEMS (LOINC_CODE);
CREATE INDEX CLABITEMS_PRODUCT_IX ON SKMST_CLABITEMS (PRODUCT_ID);

-- SKMST_CUSTOMERS
CREATE INDEX CUSTOMERS_KOTA_PROV_IX ON SKMST_CUSTOMERS (KOTA_ID, PROV_ID);
CREATE INDEX CUSTOMERS_PROV_IX ON SKMST_CUSTOMERS (PROV_ID);

-- SKMST_DESAS
CREATE INDEX DESAS_KEC_IX ON SKMST_DESAS (KEC_ID);

-- SKMST_DOCTORS
CREATE INDEX DOCTORS_POLI_IX ON SKMST_DOCTORS (POLI_ID);

-- SKMST_KABUPATENS
CREATE INDEX KABUPATENS_PROP_IX ON SKMST_KABUPATENS (PROP_ID);

-- SKMST_KECAMATANS
CREATE INDEX KECAMATANS_KAB_IX ON SKMST_KECAMATANS (KAB_ID);

-- SKMST_KOTAS
CREATE INDEX KOTAS_PROV_IX ON SKMST_KOTAS (PROV_ID);

-- SKMST_LOINC_CODES
CREATE INDEX LOINC_CODES_FN_2_IX ON SKMST_LOINC_CODES (UPPER("DISPLAY_ID"));
CREATE INDEX LOINC_CODES_FN_IX ON SKMST_LOINC_CODES (UPPER("DISPLAY"));

-- SKMST_PASIENS
CREATE INDEX PASIENS_DES_IX ON SKMST_PASIENS (DES_ID);
CREATE INDEX PASIENS_EDU_IX ON SKMST_PASIENS (EDU_ID);
CREATE INDEX PASIENS_JOB_IX ON SKMST_PASIENS (JOB_ID);
CREATE INDEX PASIENS_KAB_IX ON SKMST_PASIENS (KAB_ID);
CREATE INDEX PASIENS_KEC_IX ON SKMST_PASIENS (KEC_ID);
CREATE INDEX PASIENS_PROP_IX ON SKMST_PASIENS (PROP_ID);
CREATE INDEX PASIENS_REG_NAME_IX ON SKMST_PASIENS (REG_NAME);
CREATE INDEX PASIENS_REL_IX ON SKMST_PASIENS (REL_ID);

-- SKMST_PRODUCTCONTENTS
CREATE INDEX PRODUCTCONTENTS_CONT_IX ON SKMST_PRODUCTCONTENTS (CONT_ID);
CREATE INDEX PRODUCTCONTENTS_PRODUCT_IX ON SKMST_PRODUCTCONTENTS (PRODUCT_ID);
CREATE INDEX PRODUCTCONTENTS_UOM_IX ON SKMST_PRODUCTCONTENTS (UOM_ID);

-- SKMST_PRODUCTNONS
CREATE INDEX PRODUCTNONS_UOM_IX ON SKMST_PRODUCTNONS (UOM_ID);

-- SKMST_PRODUCTPAKETS
CREATE INDEX PRODUCTPAKETS_PRODUCT_IX ON SKMST_PRODUCTPAKETS (PRODUCT_ID);
CREATE INDEX PRODUCTPAKE_PRODUCT_ID_PROD_IX ON SKMST_PRODUCTPAKETS (PRODUCT_ID_PROD);

-- SKMST_PRODUCTS
CREATE INDEX PRODUCTS_CAT_IX ON SKMST_PRODUCTS (CAT_ID);
CREATE INDEX PRODUCTS_SUPP_IX ON SKMST_PRODUCTS (SUPP_ID);
CREATE INDEX PRODUCTS_UOM_IX ON SKMST_PRODUCTS (UOM_ID);
CREATE INDEX SKMST_PRODUCTS_KFA_IX ON SKMST_PRODUCTS (PRODUCT_ID_SATUSEHAT);

-- SKMST_RADIOLOGIS
CREATE INDEX RADIOLOGIS_LOINC_CODE_IX ON SKMST_RADIOLOGIS (LOINC_CODE);

-- SKMST_SCPOLIS
CREATE INDEX SCPOLIS_DAY_IX ON SKMST_SCPOLIS (DAY_ID);
CREATE INDEX SCPOLIS_DR_IX ON SKMST_SCPOLIS (DR_ID);
CREATE INDEX SCPO_POLI_DR_DAY_MULAI_PRAK_IX ON SKMST_SCPOLIS (POLI_ID, DR_ID, DAY_ID, MULAI_PRAKTEK, SELESAI_PRAKTEK);

-- SKMST_SIGNA_CATATANS
CREATE INDEX SIGNA_CATATANS_ACTIVE_IX ON SKMST_SIGNA_CATATANS (ACTIVE_STATUS);

-- SKMST_SNOMED_CODES
CREATE INDEX SNOMED_CODES_FN_2_IX ON SKMST_SNOMED_CODES (UPPER("DISPLAY_ID"));
CREATE INDEX SNOMED_CODES_FN_IX ON SKMST_SNOMED_CODES (UPPER("DISPLAY_EN"));
CREATE INDEX SNOMED_CODES_VALUE_SET_IX ON SKMST_SNOMED_CODES (VALUE_SET);

-- SKMST_USERAPPLICATIONS
CREATE INDEX USERAPPLICATIONS_APP_CODE_IX ON SKMST_USERAPPLICATIONS (APP_CODE);
CREATE INDEX USERAPPLICATIONS_USER_CODE_IX ON SKMST_USERAPPLICATIONS (USER_CODE);

-- SKTXN_CASHINDTLS
CREATE INDEX CASHINDTLS_CASHIN_NO_IX ON SKTXN_CASHINDTLS (CASHIN_NO);
CREATE INDEX CASHINDTLS_SLS_NO_IX ON SKTXN_CASHINDTLS (SLS_NO);

-- SKTXN_CASHINHDRS
CREATE INDEX CASHINHDRS_CB_IX ON SKTXN_CASHINHDRS (CB_ID);
CREATE INDEX CASHINHDRS_CM_IX ON SKTXN_CASHINHDRS (CM_ID);
CREATE INDEX CASHINHDRS_KASIR_IX ON SKTXN_CASHINHDRS (KASIR_ID);

-- SKTXN_CASHOUTDTLNONS
CREATE INDEX CASHOUTDTLNONS_CASHOUT_NO_IX ON SKTXN_CASHOUTDTLNONS (CASHOUT_NO);
CREATE INDEX IDX_CODTLNONS_RCVNO ON SKTXN_CASHOUTDTLNONS (RCV_NO);

-- SKTXN_CASHOUTDTLS
CREATE INDEX CASHOUTDTLS_CASHOUT_NO_IX ON SKTXN_CASHOUTDTLS (CASHOUT_NO);
CREATE INDEX CASHOUTDTLS_RCV_NO_IX ON SKTXN_CASHOUTDTLS (RCV_NO);

-- SKTXN_CASHOUTHDRNONS
CREATE INDEX CASHOUTHDRNONS_CB_IX ON SKTXN_CASHOUTHDRNONS (CB_ID);
CREATE INDEX CASHOUTHDRNONS_KASIR_IX ON SKTXN_CASHOUTHDRNONS (KASIR_ID);
CREATE INDEX CASHOUTHDRNONS_SUPP_IX ON SKTXN_CASHOUTHDRNONS (SUPP_ID);

-- SKTXN_CASHOUTHDRS
CREATE INDEX CASHOUTHDRS_CB_IX ON SKTXN_CASHOUTHDRS (CB_ID);
CREATE INDEX CASHOUTHDRS_KASIR_IX ON SKTXN_CASHOUTHDRS (KASIR_ID);
CREATE INDEX CASHOUTHDRS_SUPP_IX ON SKTXN_CASHOUTHDRS (SUPP_ID);

-- SKTXN_CHECKUPDTLS
CREATE INDEX CHECKUPDTLS_CHECKUP_NO_IX ON SKTXN_CHECKUPDTLS (CHECKUP_NO);
CREATE INDEX CHECKUPDTLS_CLABITEM_IX ON SKTXN_CHECKUPDTLS (CLABITEM_ID);

-- SKTXN_CHECKUPHDRS
CREATE INDEX CHECKUPHDRS_DR_IX ON SKTXN_CHECKUPHDRS (DR_ID);
CREATE INDEX CHECKUPHDRS_KASIR_IX ON SKTXN_CHECKUPHDRS (KASIR_ID);
CREATE INDEX CHECKUPHDRS_REG_NO_IX ON SKTXN_CHECKUPHDRS (REG_NO);

-- SKTXN_CHECKUPOBATS
CREATE INDEX CHECKUPOBATS_CHECKUP_NO_IX ON SKTXN_CHECKUPOBATS (CHECKUP_NO);
CREATE INDEX CHECKUPOBATS_PRODUCT_IX ON SKTXN_CHECKUPOBATS (PRODUCT_ID);

-- SKTXN_CHECKUPOUTDTLS
CREATE INDEX CHECKUPOUTDTLS_CHECKUP_NO_IX ON SKTXN_CHECKUPOUTDTLS (CHECKUP_NO);

-- SKTXN_RCVDTLNONS
CREATE INDEX IDX_RCVDTLNONS_RCVNO ON SKTXN_RCVDTLNONS (RCV_NO);
CREATE INDEX RCVDTLNONS_PRODUCT_IX ON SKTXN_RCVDTLNONS (PRODUCT_ID);

-- SKTXN_RCVDTLS
CREATE INDEX RCVDTLS_PRODUCT_IX ON SKTXN_RCVDTLS (PRODUCT_ID);
CREATE INDEX RCVDTLS_RCV_NO_IX ON SKTXN_RCVDTLS (RCV_NO);

-- SKTXN_RCVHDRNONS
CREATE INDEX RCVHDRNONS_CB_IX ON SKTXN_RCVHDRNONS (CB_ID);
CREATE INDEX RCVHDRNONS_KASIR_IX ON SKTXN_RCVHDRNONS (KASIR_ID);
CREATE INDEX RCVHDRNONS_SUPP_IX ON SKTXN_RCVHDRNONS (SUPP_ID);

-- SKTXN_RCVHDRS
CREATE INDEX RCVHDRS_CB_IX ON SKTXN_RCVHDRS (CB_ID);
CREATE INDEX RCVHDRS_KASIR_IX ON SKTXN_RCVHDRS (KASIR_ID);
CREATE INDEX RCVHDRS_SUPP_IX ON SKTXN_RCVHDRS (SUPP_ID);

-- SKTXN_RCVPAYMENTNONS
CREATE INDEX RCVPAYMENTNONS_RCV_NO_IX ON SKTXN_RCVPAYMENTNONS (RCV_NO);

-- SKTXN_RCVPAYMENTS
CREATE INDEX RCVPAYMENTS_RCV_NO_IX ON SKTXN_RCVPAYMENTS (RCV_NO);

-- SKTXN_RJACCDOCS
CREATE INDEX RJACCDOCS_ACCDOC_IX ON SKTXN_RJACCDOCS (ACCDOC_ID);
CREATE INDEX RJACCDOCS_DR_IX ON SKTXN_RJACCDOCS (DR_ID);
CREATE INDEX RJACCDOCS_RJ_NO_IX ON SKTXN_RJACCDOCS (RJ_NO);

-- SKTXN_RJACTEMPS
CREATE INDEX RJACTEMPS_ACTE_IX ON SKTXN_RJACTEMPS (ACTE_ID);
CREATE INDEX RJACTEMPS_RJ_NO_IX ON SKTXN_RJACTEMPS (RJ_NO);

-- SKTXN_RJACTPARAMS
CREATE INDEX RJACTPARAMS_PACT_IX ON SKTXN_RJACTPARAMS (PACT_ID);
CREATE INDEX RJACTPARAMS_RJ_NO_IX ON SKTXN_RJACTPARAMS (RJ_NO);

-- SKTXN_RJCASHINS
CREATE INDEX RJCASHINS_CB_IX ON SKTXN_RJCASHINS (CB_ID);
CREATE INDEX RJCASHINS_KASIR_IX ON SKTXN_RJCASHINS (KASIR_ID);
CREATE INDEX RJCASHINS_RJ_NO_IX ON SKTXN_RJCASHINS (RJ_NO);
CREATE INDEX RJCASHINS_SHIFT_IX ON SKTXN_RJCASHINS (SHIFT);

-- SKTXN_RJDTLS
CREATE INDEX RJDTLS_DIAG_IX ON SKTXN_RJDTLS (DIAG_ID);
CREATE INDEX RJDTLS_RJ_NO_IX ON SKTXN_RJDTLS (RJ_NO);

-- SKTXN_RJHDRS
CREATE INDEX RJHDRS_CB_IX ON SKTXN_RJHDRS (CB_ID);
CREATE INDEX RJHDRS_DR_IX ON SKTXN_RJHDRS (DR_ID);
CREATE INDEX RJHDRS_KASIR_IX ON SKTXN_RJHDRS (KASIR_ID);
CREATE INDEX RJHDRS_KLAIM_IX ON SKTXN_RJHDRS (KLAIM_ID);
CREATE INDEX RJHDRS_POLI_IX ON SKTXN_RJHDRS (POLI_ID);
CREATE INDEX RJHDRS_REG_NO_IX ON SKTXN_RJHDRS (REG_NO);
CREATE INDEX RJHDRS_SHIFT_IX ON SKTXN_RJHDRS (SHIFT);

-- SKTXN_RJLABS
CREATE INDEX RJLABS_CHECKUP_NO_IX ON SKTXN_RJLABS (CHECKUP_NO);
CREATE INDEX RJLABS_RJ_NO_IX ON SKTXN_RJLABS (RJ_NO);

-- SKTXN_RJOBATRACIKANS
CREATE INDEX RJOBATRACIKANS_ACTE_DTL_IX ON SKTXN_RJOBATRACIKANS (ACTE_DTL);
CREATE INDEX RJOBATRACIKANS_PACT_DTL_IX ON SKTXN_RJOBATRACIKANS (PACT_DTL);
CREATE INDEX RJOBATRACIKANS_RJHN_DTL_IX ON SKTXN_RJOBATRACIKANS (RJHN_DTL);
CREATE INDEX RJOBATRACIKANS_RJOBAT_DTL_IX ON SKTXN_RJOBATRACIKANS (RJOBAT_DTL);
CREATE INDEX RJOBATRACIKANS_RJ_NO_IX ON SKTXN_RJOBATRACIKANS (RJ_NO);

-- SKTXN_RJOBATS
CREATE INDEX RJOBATS_ACTE_DTL_IX ON SKTXN_RJOBATS (ACTE_DTL);
CREATE INDEX RJOBATS_EXP_DATE_IX ON SKTXN_RJOBATS (EXP_DATE);
CREATE INDEX RJOBATS_PACT_DTL_IX ON SKTXN_RJOBATS (PACT_DTL);
CREATE INDEX RJOBATS_PRODUCT_IX ON SKTXN_RJOBATS (PRODUCT_ID);
CREATE INDEX RJOBATS_RJHN_DTL_IX ON SKTXN_RJOBATS (RJHN_DTL);
CREATE INDEX RJOBATS_RJ_NO_IX ON SKTXN_RJOBATS (RJ_NO);

-- SKTXN_RJOTHERS
CREATE INDEX RJOTHERS_ACTE_DTL_IX ON SKTXN_RJOTHERS (ACTE_DTL);
CREATE INDEX RJOTHERS_OTHER_IX ON SKTXN_RJOTHERS (OTHER_ID);
CREATE INDEX RJOTHERS_PACT_DTL_IX ON SKTXN_RJOTHERS (PACT_DTL);
CREATE INDEX RJOTHERS_RJHN_DTL_IX ON SKTXN_RJOTHERS (RJHN_DTL);
CREATE INDEX RJOTHERS_RJ_NO_IX ON SKTXN_RJOTHERS (RJ_NO);

-- SKTXN_RJRADS
CREATE INDEX RJRADS_RAD_IX ON SKTXN_RJRADS (RAD_ID);
CREATE INDEX RJRADS_RJ_NO_IX ON SKTXN_RJRADS (RJ_NO);

-- SKTXN_RJUPLOADBPJSES
CREATE INDEX RJUPLOADBPJSES_RJ_NO_IX ON SKTXN_RJUPLOADBPJSES (RJ_NO);

-- SKTXN_SALDOAWALAKUNS
CREATE INDEX SALDOAWALAKUNS_ACC_IX ON SKTXN_SALDOAWALAKUNS (ACC_ID);

-- SKTXN_SALDOAWALHUTANGS
CREATE INDEX SALDOAWALHUTANGS_SUPP_IX ON SKTXN_SALDOAWALHUTANGS (SUPP_ID);

-- SKTXN_SALDOAWALPIUTANGS
CREATE INDEX SALDOAWALPIUTANGS_CM_IX ON SKTXN_SALDOAWALPIUTANGS (CM_ID);

-- SKTXN_SALDOAWALSTOCKS
CREATE INDEX SALDOAWALSTOCKS_PRODUCT_IX ON SKTXN_SALDOAWALSTOCKS (PRODUCT_ID);

-- SKTXN_SALDOAWALSTOCKSNON
CREATE INDEX SALDOAWALSTOCKSNON_PRODUCT_IX ON SKTXN_SALDOAWALSTOCKSNON (PRODUCT_ID);

-- SKTXN_SLSDTLS
CREATE INDEX SLSDTLS_PRODUCT_IX ON SKTXN_SLSDTLS (PRODUCT_ID);
CREATE INDEX SLSDTLS_SLS_NO_IX ON SKTXN_SLSDTLS (SLS_NO);

-- SKTXN_SLSHDRS
CREATE INDEX SLSHDRS_CB_IX ON SKTXN_SLSHDRS (CB_ID);
CREATE INDEX SLSHDRS_CM_IX ON SKTXN_SLSHDRS (CM_ID);
CREATE INDEX SLSHDRS_KASIR_IX ON SKTXN_SLSHDRS (KASIR_ID);

-- SKTXN_SLSKIRIMS
CREATE INDEX SLSKIRIMS_KOTA_PROV_IX ON SKTXN_SLSKIRIMS (KOTA_ID, PROV_ID);
CREATE INDEX SLSKIRIMS_PROV_IX ON SKTXN_SLSKIRIMS (PROV_ID);

-- SKTXN_SLSPAYMENTS
CREATE INDEX SLSPAYMENTS_SLS_NO_IX ON SKTXN_SLSPAYMENTS (SLS_NO);

-- SKTXN_SOWHS
CREATE INDEX SOWHS_KASIR_IX ON SKTXN_SOWHS (KASIR_ID);
CREATE INDEX SOWHS_PRODUCT_SO_DATE_IX ON SKTXN_SOWHS (PRODUCT_ID, SO_DATE);

-- SKTXN_SOWHSNON
CREATE INDEX IDX_SOWHSNON_PRD ON SKTXN_SOWHSNON (PRODUCT_ID);
CREATE INDEX SOWHSNON_KASIR_IX ON SKTXN_SOWHSNON (KASIR_ID);

-- SKTXN_TUCASHINS
CREATE INDEX TUCASHINS_CB_IX ON SKTXN_TUCASHINS (CB_ID);
CREATE INDEX TUCASHINS_KASIR_IX ON SKTXN_TUCASHINS (KASIR_ID);
CREATE INDEX TUCASHINS_TUCICO_IX ON SKTXN_TUCASHINS (TUCICO_ID);

-- SKTXN_TUCASHOUTS
CREATE INDEX TUCASHOUTS_CB_IX ON SKTXN_TUCASHOUTS (CB_ID);
CREATE INDEX TUCASHOUTS_KASIR_IX ON SKTXN_TUCASHOUTS (KASIR_ID);
CREATE INDEX TUCASHOUTS_TUCICO_IX ON SKTXN_TUCASHOUTS (TUCICO_ID);
