<?php

namespace App\Support\Keuangan;

/**
 * KATALOG CABANG JURNAL siklik — SUMBER KEBENARAN definisi jurnal untuk laporan keuangan web.
 *
 * Diturunkan 2026-09-11 secara mekanis dari DDL view SKVIEW_ACCOUNTS (46 cabang = 23 pasang cermin), lalu dirawat DI SINI.
 * View SKVIEW_ACCOUNTS / _LABARUGI / _NERACA kini hanya untuk form Oracle 6i; halaman web (Buku Besar,
 * Cek Saldo Kas, Laba Rugi, Neraca) membaca tabel transaksi langsung lewat App\Support\Keuangan\Jurnal.
 *
 * Tiap cabang = satu SELECT 6 kolom (urutan sama dengan view; siklik tidak punya kolom SHIFT):
 *   label      : ekspresi TXN_NAME (kata pertama dipakai rekap per jenis)
 *   akun       : TXN_ACC   — akun pemilik baris (debit/kredit = D/K akun ini)
 *   akunLawan  : TXN_ACC_K — akun lawan
 *   tanggal    : kolom tanggal tabel sumber   debit/kredit : ekspresi TXN_D / TXN_K
 *   from / where : klausa FROM / WHERE (boleh kosong)
 * Akun ditulis 'conf:N' = akun konfigurasi skacc_confacctxns.conf_id = N (dipangkas di PHP bila bukan akun
 * yang diminta), atau kolom akun tabel sumber (b.acc_id = skacc_carabayars / skacc_tucicos) yang diberi predikat.
 * HPP (cabang view SKVIEW_ACCOUNTS_LABARUGI) TIDAK di sini — dihitung App\Support\Keuangan\Hpp dan disisipkan
 * Jurnal sebagai cabang semu per tahun, karena view HPP-nya membaca SKVIEW_ACCOUNTS (hasil tak stabil di 10g).
 *
 * Catatan asimetri warisan view (dipertahankan apa adanya, tinjau bila ingin diseragamkan):
 *   - RCV DISKON TOTAL / MATERAI / PPN: cabang cermin kedua memfilter nilai > 0, cabang pertama tidak.
 *   - BAYAR APOTEK/RJ (cash in) dan BAYAR RCV (cash out) tidak memfilter status dokumen.
 *   - Label 'SLS DISKON ITEM TRANSAKSI' dipakai kedua cabang cermin (view aslinya begitu).
 */
final class JurnalCabang
{
    /** @return list<array{label:string,akun:string,akunLawan:string,tanggal:string,debit:string,kredit:string,from:string,where:string}> */
    public static function semua(): array
    {
        return [
            [
                'label'     => '\'BAYAR APOTEK NOTA No\'||(select string_AGG(sls_no) from SKTXN_CASHINDTLS where cashin_no=a.cashin_no)',
                'akun'      => 'b.acc_id',
                'akunLawan' => 'conf:7',
                'tanggal'   => 'cashin_date',
                'debit'     => 'cashin_value',
                'kredit'    => '0',
                'from'      => 'SKTXN_CASHINHDRS a, SKACC_CARABAYARS b',
                'where'     => 'a.cb_id=b.cb_id',
            ],
            [
                'label'     => '\'BAYAR PIUTANG APOTEK NOTA No\'||(select string_AGG(sls_no) from SKTXN_CASHINDTLS where cashin_no=a.cashin_no)',
                'akun'      => 'conf:7',
                'akunLawan' => 'b.acc_id',
                'tanggal'   => 'cashin_date',
                'debit'     => '0',
                'kredit'    => 'cashin_value',
                'from'      => 'SKTXN_CASHINHDRS a, SKACC_CARABAYARS b',
                'where'     => 'a.cb_id=b.cb_id',
            ],
            [
                'label'     => '\'SLS TRANSAKSI\'',
                'akun'      => 'conf:1',
                'akunLawan' => 'conf:7',
                'tanggal'   => 'sls_date',
                'debit'     => '0',
                'kredit'    => '(select nvl(sum(nvl(qty,0)*nvl(sales_price,0)),0) from sktxn_slsdtls where sls_no=a.sls_no)',
                'from'      => 'SKTXN_SLSHDRS a',
                'where'     => 'sls_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'SLS PIUTANG TRANSAKSI\'',
                'akun'      => 'conf:7',
                'akunLawan' => 'conf:1',
                'tanggal'   => 'sls_date',
                'debit'     => '(select nvl(sum(nvl(qty,0)*nvl(sales_price,0)),0) from sktxn_slsdtls where sls_no=a.sls_no)',
                'kredit'    => '0',
                'from'      => 'SKTXN_SLSHDRS a',
                'where'     => 'sls_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'SLS DISKON ITEM TRANSAKSI\'',
                'akun'      => 'conf:5',
                'akunLawan' => 'conf:7',
                'tanggal'   => 'sls_date',
                'debit'     => '(select nvl( sum(/**/((nvl(qty,0)*nvl(sales_price,0))*nvl(dtl_persen,0)/100)/**/+/**/nvl(dtl_diskon,0)/**/),0) from sktxn_slsdtls where sls_no=a.sls_no)',
                'kredit'    => '0',
                'from'      => 'SKTXN_SLSHDRS a',
                'where'     => 'sls_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'SLS DISKON ITEM TRANSAKSI\'',
                'akun'      => 'conf:7',
                'akunLawan' => 'conf:5',
                'tanggal'   => 'sls_date',
                'debit'     => '0',
                'kredit'    => '(select nvl( sum(/**/((nvl(qty,0)*nvl(sales_price,0))*nvl(dtl_persen,0)/100)/**/+/**/nvl(dtl_diskon,0)/**/),0) from sktxn_slsdtls where sls_no=a.sls_no)',
                'from'      => 'SKTXN_SLSHDRS a',
                'where'     => 'sls_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'SLS DISKON TOTAL TRANSAKSI\'',
                'akun'      => 'conf:5',
                'akunLawan' => 'conf:7',
                'tanggal'   => 'sls_date',
                'debit'     => 'nvl(sls_diskon,0)',
                'kredit'    => '0',
                'from'      => 'SKTXN_SLSHDRS a',
                'where'     => 'sls_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'SLS DISKON TOTAL TRANSAKSI\'',
                'akun'      => 'conf:7',
                'akunLawan' => 'conf:5',
                'tanggal'   => 'sls_date',
                'debit'     => '0',
                'kredit'    => 'nvl(sls_diskon,0)',
                'from'      => 'SKTXN_SLSHDRS a',
                'where'     => 'sls_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'BAYAR RCV CASH OUT\'',
                'akun'      => 'b.acc_id',
                'akunLawan' => 'conf:8',
                'tanggal'   => 'cashout_date',
                'debit'     => '0',
                'kredit'    => 'cashout_value',
                'from'      => 'SKTXN_CASHOUTHDRS a, SKACC_CARABAYARS b',
                'where'     => 'a.cb_id=b.cb_id',
            ],
            [
                'label'     => '\'BAYAR HUTANG RCV\'',
                'akun'      => 'conf:8',
                'akunLawan' => 'b.acc_id',
                'tanggal'   => 'cashout_date',
                'debit'     => 'cashout_value',
                'kredit'    => '0',
                'from'      => 'SKTXN_CASHOUTHDRS a, SKACC_CARABAYARS b',
                'where'     => 'a.cb_id=b.cb_id',
            ],
            [
                'label'     => '\'RCV TRANSAKSI\'',
                'akun'      => 'conf:2',
                'akunLawan' => 'conf:8',
                'tanggal'   => 'RCV_date',
                'debit'     => '(select nvl(sum(nvl(qty,0)*nvl(cost_price,0)),0) from sktxn_RCVdtls where RCV_no=a.RCV_no)',
                'kredit'    => '0',
                'from'      => 'SKTXN_RCVHDRS a',
                'where'     => 'RCV_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'RCV HUTANG TRANSAKSI\'',
                'akun'      => 'conf:8',
                'akunLawan' => 'conf:2',
                'tanggal'   => 'RCV_date',
                'debit'     => '0',
                'kredit'    => '(select nvl(sum(nvl(qty,0)*nvl(cost_price,0)),0) from sktxn_RCVdtls where RCV_no=a.RCV_no)',
                'from'      => 'SKTXN_RCVHDRS a',
                'where'     => 'RCV_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'RCV DISKON ITEM TRANSAKSI\'',
                'akun'      => 'conf:6',
                'akunLawan' => 'conf:8',
                'tanggal'   => 'RCV_date',
                'debit'     => '0',
                'kredit'    => '(select sum(nvl(qty,0)*nvl(cost_price,0))- sum( /*persen1*/(nvl(qty,0)*nvl(cost_price,0))/**/-/**/((nvl(qty,0)*nvl(cost_price,0))*nvl(dtl_persen,0)/100)/**/-/**/nvl(dtl_diskon,0)- /*persen2*/(((nvl(qty,0)*nvl(cost_price,0))/**/-/**/((nvl(qty,0)*nvl(cost_price,0))*nvl(dtl_persen,0)/100)/**/-/**/nvl(dtl_diskon,0))* (nvl(dtl_persen1,0)/100))-/**/nvl(dtl_diskon1,0)) from sktxn_RCVdtls where RCV_no=a.RCV_no)',
                'from'      => 'SKTXN_RCVHDRS a',
                'where'     => 'RCV_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'RCV DISKON ITEM TRANSAKSI\'',
                'akun'      => 'conf:8',
                'akunLawan' => 'conf:6',
                'tanggal'   => 'RCV_date',
                'debit'     => '(select sum(nvl(qty,0)*nvl(cost_price,0))- sum( /*persen1*/(nvl(qty,0)*nvl(cost_price,0))/**/-/**/((nvl(qty,0)*nvl(cost_price,0))*nvl(dtl_persen,0)/100)/**/-/**/nvl(dtl_diskon,0)- /*persen2*/(((nvl(qty,0)*nvl(cost_price,0))/**/-/**/((nvl(qty,0)*nvl(cost_price,0))*nvl(dtl_persen,0)/100)/**/-/**/nvl(dtl_diskon,0))* (nvl(dtl_persen1,0)/100))-/**/nvl(dtl_diskon1,0)) from sktxn_RCVdtls where RCV_no=a.RCV_no)',
                'kredit'    => '0',
                'from'      => 'SKTXN_RCVHDRS a',
                'where'     => 'RCV_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'RCV DISKON TOTAL TRANSAKSI\'',
                'akun'      => 'conf:6',
                'akunLawan' => 'conf:8',
                'tanggal'   => 'RCV_date',
                'debit'     => '0',
                'kredit'    => 'nvl(RCV_diskon,0)',
                'from'      => 'SKTXN_RCVHDRS a',
                'where'     => 'RCV_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'RCV DISKON TOTAL TRANSAKSI\'',
                'akun'      => 'conf:8',
                'akunLawan' => 'conf:6',
                'tanggal'   => 'RCV_date',
                'debit'     => 'nvl(RCV_diskon,0)',
                'kredit'    => '0',
                'from'      => 'SKTXN_RCVHDRS a',
                'where'     => 'RCV_status in (\'H\',\'L\') and nvl(RCV_diskon,0)>0',
            ],
            [
                'label'     => '\'RCV MATERAI TOTAL TRANSAKSI\'',
                'akun'      => 'conf:8',
                'akunLawan' => 'conf:12',
                'tanggal'   => 'RCV_date',
                'debit'     => '0',
                'kredit'    => 'nvl(RCV_materai,0)',
                'from'      => 'SKTXN_RCVHDRS a',
                'where'     => 'RCV_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'RCV MATERAI TOTAL TRANSAKSI\'',
                'akun'      => 'conf:12',
                'akunLawan' => 'conf:8',
                'tanggal'   => 'RCV_date',
                'debit'     => 'nvl(RCV_materai,0)',
                'kredit'    => '0',
                'from'      => 'SKTXN_RCVHDRS a',
                'where'     => 'RCV_status in (\'H\',\'L\') and nvl(RCV_materai,0)>0',
            ],
            [
                'label'     => '\'RCV PPN TOTAL TRANSAKSI\'',
                'akun'      => 'conf:8',
                'akunLawan' => 'conf:13',
                'tanggal'   => 'RCV_date',
                'debit'     => '0',
                'kredit'    => 'nvl(totalppn,0)',
                'from'      => 'SKVIEW_RCVHDRS a',
                'where'     => 'RCV_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'RCV PPN TOTAL TRANSAKSI\'',
                'akun'      => 'conf:13',
                'akunLawan' => 'conf:8',
                'tanggal'   => 'RCV_date',
                'debit'     => 'nvl(totalppn,0)',
                'kredit'    => '0',
                'from'      => 'SKVIEW_RCVHDRS a',
                'where'     => 'RCV_status in (\'H\',\'L\') and nvl(totalppn,0)>0',
            ],
            [
                'label'     => '\'CASH OUT\'',
                'akun'      => 'b.acc_id',
                'akunLawan' => '(select y.acc_id from SKTXN_TUCASHOUTS x,SKACC_CARABAYARS y where x.CB_ID=y.CB_ID and CO_STATUS=\'L\' and CO_NO=a.co_no)',
                'tanggal'   => 'co_date',
                'debit'     => 'nvl(co_nominal,0)',
                'kredit'    => '0',
                'from'      => 'SKTXN_TUCASHOUTS a, SKACC_TUCICOS b',
                'where'     => 'a.TUCICO_ID=b.TUCICO_ID and CO_STATUS=\'L\'',
            ],
            [
                'label'     => '\'CASH OUT\'',
                'akun'      => 'b.acc_id',
                'akunLawan' => '(select y.acc_id from SKTXN_TUCASHOUTS x,SKACC_TUCICOS y where x.TUCICO_ID=y.TUCICO_ID and CO_STATUS=\'L\' and CO_NO=a.co_no)',
                'tanggal'   => 'co_date',
                'debit'     => '0',
                'kredit'    => 'nvl(co_nominal,0)',
                'from'      => 'SKTXN_TUCASHOUTS a, SKACC_CARABAYARS b',
                'where'     => 'a.CB_ID=b.CB_ID and CO_STATUS=\'L\'',
            ],
            [
                'label'     => '\'CASH IN\'',
                'akun'      => 'b.acc_id',
                'akunLawan' => '(select y.acc_id from SKTXN_TUCASHINS x,SKACC_CARABAYARS y where x.CB_ID=y.CB_ID and CI_STATUS=\'L\' and CI_NO=a.ci_no)',
                'tanggal'   => 'ci_date',
                'debit'     => '0',
                'kredit'    => 'nvl(ci_nominal,0)',
                'from'      => 'SKTXN_TUCASHINS a, SKACC_TUCICOS b',
                'where'     => 'a.TUCIco_ID=b.TUCIco_ID and ci_STATUS=\'L\'',
            ],
            [
                'label'     => '\'CASH IN\'',
                'akun'      => 'b.acc_id',
                'akunLawan' => '(select y.acc_id from SKTXN_TUCASHINS x,SKACC_TUCICOS y where x.TUCICO_ID=y.TUCICO_ID and CI_STATUS=\'L\' and CI_NO=a.ci_no)',
                'tanggal'   => 'ci_date',
                'debit'     => 'nvl(ci_nominal,0)',
                'kredit'    => '0',
                'from'      => 'SKTXN_TUCASHINS a, SKACC_CARABAYARS b',
                'where'     => 'a.CB_ID=b.CB_ID and ci_STATUS=\'L\'',
            ],
            [
                'label'     => '\'BAYAR RJ \'||RJC_DESC',
                'akun'      => 'b.acc_id',
                'akunLawan' => 'conf:7',
                'tanggal'   => 'RJC_DATE',
                'debit'     => 'RJC_NOMINAL',
                'kredit'    => '0',
                'from'      => 'SKTXN_RJCASHINS a, SKACC_CARABAYARS b',
                'where'     => 'a.cb_id=b.cb_id',
            ],
            [
                'label'     => '\'BAYAR PIUTANG RJ \'||RJC_DESC',
                'akun'      => 'conf:7',
                'akunLawan' => 'b.acc_id',
                'tanggal'   => 'RJC_DATE',
                'debit'     => '0',
                'kredit'    => 'RJC_NOMINAL',
                'from'      => 'SKTXN_RJCASHINS a, SKACC_CARABAYARS b',
                'where'     => 'a.cb_id=b.cb_id',
            ],
            [
                'label'     => '\'RJ JD TRANSAKSI\'',
                'akun'      => 'conf:1',
                'akunLawan' => 'conf:7',
                'tanggal'   => 'rj_date',
                'debit'     => '0',
                'kredit'    => '(select nvl(sum(ACCDOC_price),0) from sktxn_rjaccdocs where rj_no=a.rj_no)',
                'from'      => 'sktxn_rjhdrs a',
                'where'     => 'txn_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'RJ JD PIUTANG TRANSAKSI\'',
                'akun'      => 'conf:7',
                'akunLawan' => 'conf:1',
                'tanggal'   => 'rj_date',
                'debit'     => '(select nvl(sum(ACCDOC_price),0) from sktxn_rjaccdocs where rj_no=a.rj_no)',
                'kredit'    => '0',
                'from'      => 'sktxn_rjhdrs a',
                'where'     => 'txn_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'RJ OBAT TRANSAKSI\'',
                'akun'      => 'conf:1',
                'akunLawan' => 'conf:7',
                'tanggal'   => 'rj_date',
                'debit'     => '0',
                'kredit'    => '(select nvl(sum(qty*price),0) from sktxn_rjobats where rj_no=a.rj_no)',
                'from'      => 'sktxn_rjhdrs a',
                'where'     => 'txn_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'RJ OBAT PIUTANG TRANSAKSI\'',
                'akun'      => 'conf:7',
                'akunLawan' => 'conf:1',
                'tanggal'   => 'rj_date',
                'debit'     => '(select nvl(sum(qty*price),0) from sktxn_rjobats where rj_no=a.rj_no)',
                'kredit'    => '0',
                'from'      => 'sktxn_rjhdrs a',
                'where'     => 'txn_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'RJ JK TRANSAKSI\'',
                'akun'      => 'conf:1',
                'akunLawan' => 'conf:7',
                'tanggal'   => 'rj_date',
                'debit'     => '0',
                'kredit'    => '(select nvl(sum(ACTE_price),0) from SKTXN_RJACTEMPS where rj_no=a.rj_no)',
                'from'      => 'sktxn_rjhdrs a',
                'where'     => 'txn_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'RJ JK PIUTANG TRANSAKSI\'',
                'akun'      => 'conf:7',
                'akunLawan' => 'conf:1',
                'tanggal'   => 'rj_date',
                'debit'     => '(select nvl(sum(ACTE_price),0) from SKTXN_RJACTEMPS where rj_no=a.rj_no)',
                'kredit'    => '0',
                'from'      => 'sktxn_rjhdrs a',
                'where'     => 'txn_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'RJ LAB TRANSAKSI\'',
                'akun'      => 'conf:1',
                'akunLawan' => 'conf:7',
                'tanggal'   => 'rj_date',
                'debit'     => '0',
                'kredit'    => '(select nvl(sum(lab_price),0) from sktxn_rjlabs where rj_no=a.rj_no)',
                'from'      => 'sktxn_rjhdrs a',
                'where'     => 'txn_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'RJ LAB PIUTANG TRANSAKSI\'',
                'akun'      => 'conf:7',
                'akunLawan' => 'conf:1',
                'tanggal'   => 'rj_date',
                'debit'     => '(select nvl(sum(lab_price),0) from sktxn_rjlabs where rj_no=a.rj_no)',
                'kredit'    => '0',
                'from'      => 'sktxn_rjhdrs a',
                'where'     => 'txn_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'RJ JM TRANSAKSI\'',
                'akun'      => 'conf:1',
                'akunLawan' => 'conf:7',
                'tanggal'   => 'rj_date',
                'debit'     => '0',
                'kredit'    => '(select nvl(sum(pact_price),0) from SKTXN_RJACTPARAMS where rj_no=a.rj_no)',
                'from'      => 'sktxn_rjhdrs a',
                'where'     => 'txn_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'RJ JM PIUTANG TRANSAKSI\'',
                'akun'      => 'conf:7',
                'akunLawan' => 'conf:1',
                'tanggal'   => 'rj_date',
                'debit'     => '(select nvl(sum(pact_price),0) from SKTXN_RJACTPARAMS where rj_no=a.rj_no)',
                'kredit'    => '0',
                'from'      => 'sktxn_rjhdrs a',
                'where'     => 'txn_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'RJ RAD TRANSAKSI\'',
                'akun'      => 'conf:1',
                'akunLawan' => 'conf:7',
                'tanggal'   => 'rj_date',
                'debit'     => '0',
                'kredit'    => '(select nvl(sum(rad_price),0) from sktxn_rjrads where rj_no=a.rj_no)',
                'from'      => 'sktxn_rjhdrs a',
                'where'     => 'txn_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'RJ RAD PIUTANG TRANSAKSI\'',
                'akun'      => 'conf:7',
                'akunLawan' => 'conf:1',
                'tanggal'   => 'rj_date',
                'debit'     => '(select nvl(sum(rad_price),0) from sktxn_rjrads where rj_no=a.rj_no)',
                'kredit'    => '0',
                'from'      => 'sktxn_rjhdrs a',
                'where'     => 'txn_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'RJ LAIN TRANSAKSI\'',
                'akun'      => 'conf:1',
                'akunLawan' => 'conf:7',
                'tanggal'   => 'rj_date',
                'debit'     => '0',
                'kredit'    => '(select nvl(sum(other_price),0) from sktxn_rjothers where rj_no=a.rj_no)',
                'from'      => 'sktxn_rjhdrs a',
                'where'     => 'txn_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'RJ LAIN PIUTANG TRANSAKSI\'',
                'akun'      => 'conf:7',
                'akunLawan' => 'conf:1',
                'tanggal'   => 'rj_date',
                'debit'     => '(select nvl(sum(other_price),0) from sktxn_rjothers where rj_no=a.rj_no)',
                'kredit'    => '0',
                'from'      => 'sktxn_rjhdrs a',
                'where'     => 'txn_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'RJ RJ ADMIN TRANSAKSI\'',
                'akun'      => 'conf:1',
                'akunLawan' => 'conf:7',
                'tanggal'   => 'rj_date',
                'debit'     => '0',
                'kredit'    => 'rj_admin',
                'from'      => 'sktxn_rjhdrs a',
                'where'     => 'txn_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'RJ RJ ADMIN PIUTANG TRANSAKSI\'',
                'akun'      => 'conf:7',
                'akunLawan' => 'conf:1',
                'tanggal'   => 'rj_date',
                'debit'     => 'rj_admin',
                'kredit'    => '0',
                'from'      => 'sktxn_rjhdrs a',
                'where'     => 'txn_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'RJ RS ADMIN TRANSAKSI\'',
                'akun'      => 'conf:1',
                'akunLawan' => 'conf:7',
                'tanggal'   => 'rj_date',
                'debit'     => '0',
                'kredit'    => 'rs_admin',
                'from'      => 'sktxn_rjhdrs a',
                'where'     => 'txn_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'RJ RS ADMIN PIUTANG TRANSAKSI\'',
                'akun'      => 'conf:7',
                'akunLawan' => 'conf:1',
                'tanggal'   => 'rj_date',
                'debit'     => 'rs_admin',
                'kredit'    => '0',
                'from'      => 'sktxn_rjhdrs a',
                'where'     => 'txn_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'RJ DISKON TOTAL TRANSAKSI\'',
                'akun'      => 'conf:5',
                'akunLawan' => 'conf:7',
                'tanggal'   => 'rj_date',
                'debit'     => 'nvl(RJ_DISKON,0)',
                'kredit'    => '0',
                'from'      => 'SKTXN_RJHDRS a',
                'where'     => 'txn_status in (\'H\',\'L\')',
            ],
            [
                'label'     => '\'RJ DISKON TOTAL TRANSAKSI\'',
                'akun'      => 'conf:7',
                'akunLawan' => 'conf:5',
                'tanggal'   => 'rj_date',
                'debit'     => '0',
                'kredit'    => 'nvl(RJ_DISKON,0)',
                'from'      => 'SKTXN_RJHDRS a',
                'where'     => 'txn_status in (\'H\',\'L\')',
            ],
        ];
    }
}
