-- ============================================================
-- LANGKAH 1 — Rename tabel & view ke prefix SK
-- Dibuat  : php artisan siklik:ddl-rename --prefix=SK  (2026-09-11 06:07)
-- Berhenti di error pertama. Kalau berhenti di tengah, jalankan 99_rollback.sql lalu perbaiki.
-- ============================================================
SET DEFINE OFF
SET SQLBLANKLINES ON
SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

-- Tabel (93)
ALTER TABLE DIMST_APPLICATIONS RENAME TO SKMST_APPLICATIONS;
ALTER TABLE DIMST_IDENTITASES RENAME TO SKMST_IDENTITASES;
ALTER TABLE DIMST_USERAPPLICATIONS RENAME TO SKMST_USERAPPLICATIONS;
ALTER TABLE DIMST_USERS RENAME TO SKMST_USERS;
ALTER TABLE IMMST_CONTENTS RENAME TO SKMST_CONTENTS;
ALTER TABLE IMMST_PRODUCTCONTENTS RENAME TO SKMST_PRODUCTCONTENTS;
ALTER TABLE LBMST_CLABITEMS RENAME TO SKMST_CLABITEMS;
ALTER TABLE LBMST_CLABS RENAME TO SKMST_CLABS;
ALTER TABLE LBTXN_CHECKUPDTLS RENAME TO SKTXN_CHECKUPDTLS;
ALTER TABLE LBTXN_CHECKUPHDRS RENAME TO SKTXN_CHECKUPHDRS;
ALTER TABLE LBTXN_CHECKUPOBATS RENAME TO SKTXN_CHECKUPOBATS;
ALTER TABLE LBTXN_CHECKUPOUTDTLS RENAME TO SKTXN_CHECKUPOUTDTLS;
ALTER TABLE RSMST_ACCDOCOTHERS RENAME TO SKMST_ACCDOCOTHERS;
ALTER TABLE RSMST_ACCDOCPRODUCTS RENAME TO SKMST_ACCDOCPRODUCTS;
ALTER TABLE RSMST_ACCDOCS RENAME TO SKMST_ACCDOCS;
ALTER TABLE RSMST_ACTEMPS RENAME TO SKMST_ACTEMPS;
ALTER TABLE RSMST_ACTEOTHERS RENAME TO SKMST_ACTEOTHERS;
ALTER TABLE RSMST_ACTEPRODS RENAME TO SKMST_ACTEPRODS;
ALTER TABLE RSMST_ACTPARAMEDICS RENAME TO SKMST_ACTPARAMEDICS;
ALTER TABLE RSMST_ACTPAROTHERS RENAME TO SKMST_ACTPAROTHERS;
ALTER TABLE RSMST_ACTPARPRODUCTS RENAME TO SKMST_ACTPARPRODUCTS;
ALTER TABLE RSMST_DESAS RENAME TO SKMST_DESAS;
ALTER TABLE RSMST_DOCTORS RENAME TO SKMST_DOCTORS;
ALTER TABLE RSMST_EDUCATIONS RENAME TO SKMST_EDUCATIONS;
ALTER TABLE RSMST_ENTRYTYPES RENAME TO SKMST_ENTRYTYPES;
ALTER TABLE RSMST_JOBS RENAME TO SKMST_JOBS;
ALTER TABLE RSMST_KABUPATENS RENAME TO SKMST_KABUPATENS;
ALTER TABLE RSMST_KECAMATANS RENAME TO SKMST_KECAMATANS;
ALTER TABLE RSMST_KLAIMTYPES RENAME TO SKMST_KLAIMTYPES;
ALTER TABLE RSMST_LOINC_CODES RENAME TO SKMST_LOINC_CODES;
ALTER TABLE RSMST_MEDIK RENAME TO SKMST_MEDIK;
ALTER TABLE RSMST_MSTDIAGS RENAME TO SKMST_MSTDIAGS;
ALTER TABLE RSMST_MSTPROCEDURES RENAME TO SKMST_MSTPROCEDURES;
ALTER TABLE RSMST_OTHERS RENAME TO SKMST_OTHERS;
ALTER TABLE RSMST_OUTS RENAME TO SKMST_OUTS;
ALTER TABLE RSMST_PARAMETERS RENAME TO SKMST_PARAMETERS;
ALTER TABLE RSMST_PASIENS RENAME TO SKMST_PASIENS;
ALTER TABLE RSMST_POLIS RENAME TO SKMST_POLIS;
ALTER TABLE RSMST_PROPINSIS RENAME TO SKMST_PROPINSIS;
ALTER TABLE RSMST_RADIOLOGIS RENAME TO SKMST_RADIOLOGIS;
ALTER TABLE RSMST_RELIGIONS RENAME TO SKMST_RELIGIONS;
ALTER TABLE RSMST_SNOMED_CODES RENAME TO SKMST_SNOMED_CODES;
ALTER TABLE RSTXN_RJACCDOCS RENAME TO SKTXN_RJACCDOCS;
ALTER TABLE RSTXN_RJACTEMPS RENAME TO SKTXN_RJACTEMPS;
ALTER TABLE RSTXN_RJACTPARAMS RENAME TO SKTXN_RJACTPARAMS;
ALTER TABLE RSTXN_RJCASHINS RENAME TO SKTXN_RJCASHINS;
ALTER TABLE RSTXN_RJDTLS RENAME TO SKTXN_RJDTLS;
ALTER TABLE RSTXN_RJHDRS RENAME TO SKTXN_RJHDRS;
ALTER TABLE RSTXN_RJLABS RENAME TO SKTXN_RJLABS;
ALTER TABLE RSTXN_RJOBATRACIKANS RENAME TO SKTXN_RJOBATRACIKANS;
ALTER TABLE RSTXN_RJOBATS RENAME TO SKTXN_RJOBATS;
ALTER TABLE RSTXN_RJOTHERS RENAME TO SKTXN_RJOTHERS;
ALTER TABLE RSTXN_RJRADS RENAME TO SKTXN_RJRADS;
ALTER TABLE RSTXN_RJUPLOADBPJSES RENAME TO SKTXN_RJUPLOADBPJSES;
ALTER TABLE RSTXN_SHIFTCTLS RENAME TO SKTXN_SHIFTCTLS;
ALTER TABLE SCMST_SCDAYS RENAME TO SKMST_SCDAYS;
ALTER TABLE SCMST_SCPOLIS RENAME TO SKMST_SCPOLIS;
ALTER TABLE TKACC_ACCOUNTSES RENAME TO SKACC_ACCOUNTSES;
ALTER TABLE TKACC_CARABAYARS RENAME TO SKACC_CARABAYARS;
ALTER TABLE TKACC_CONFACCTXNS RENAME TO SKACC_CONFACCTXNS;
ALTER TABLE TKACC_GR_ACCOUNTSES RENAME TO SKACC_GR_ACCOUNTSES;
ALTER TABLE TKACC_TEMACCOUNTES RENAME TO SKACC_TEMACCOUNTES;
ALTER TABLE TKACC_TEMLABARUGINERACADTLS RENAME TO SKACC_TEMLABARUGINERACADTLS;
ALTER TABLE TKACC_TEMLABARUGINERACAHDRS RENAME TO SKACC_TEMLABARUGINERACAHDRS;
ALTER TABLE TKACC_TUCICOS RENAME TO SKACC_TUCICOS;
ALTER TABLE TKMST_CATEGORIES RENAME TO SKMST_CATEGORIES;
ALTER TABLE TKMST_CUSTOMERS RENAME TO SKMST_CUSTOMERS;
ALTER TABLE TKMST_EX_IMS RENAME TO SKMST_EX_IMS;
ALTER TABLE TKMST_KASIRS RENAME TO SKMST_KASIRS;
ALTER TABLE TKMST_KOTAS RENAME TO SKMST_KOTAS;
ALTER TABLE TKMST_PRODUCTPAKETS RENAME TO SKMST_PRODUCTPAKETS;
ALTER TABLE TKMST_PRODUCTS RENAME TO SKMST_PRODUCTS;
ALTER TABLE TKMST_PROVS RENAME TO SKMST_PROVS;
ALTER TABLE TKMST_SUPPLIERS RENAME TO SKMST_SUPPLIERS;
ALTER TABLE TKMST_UOMS RENAME TO SKMST_UOMS;
ALTER TABLE TKTXN_CASHINDTLS RENAME TO SKTXN_CASHINDTLS;
ALTER TABLE TKTXN_CASHINHDRS RENAME TO SKTXN_CASHINHDRS;
ALTER TABLE TKTXN_CASHOUTDTLS RENAME TO SKTXN_CASHOUTDTLS;
ALTER TABLE TKTXN_CASHOUTHDRS RENAME TO SKTXN_CASHOUTHDRS;
ALTER TABLE TKTXN_RCVDTLS RENAME TO SKTXN_RCVDTLS;
ALTER TABLE TKTXN_RCVHDRS RENAME TO SKTXN_RCVHDRS;
ALTER TABLE TKTXN_RCVPAYMENTS RENAME TO SKTXN_RCVPAYMENTS;
ALTER TABLE TKTXN_SALDOAWALAKUNS RENAME TO SKTXN_SALDOAWALAKUNS;
ALTER TABLE TKTXN_SALDOAWALHUTANGS RENAME TO SKTXN_SALDOAWALHUTANGS;
ALTER TABLE TKTXN_SALDOAWALPIUTANGS RENAME TO SKTXN_SALDOAWALPIUTANGS;
ALTER TABLE TKTXN_SALDOAWALSTOCKS RENAME TO SKTXN_SALDOAWALSTOCKS;
ALTER TABLE TKTXN_SLSDTLS RENAME TO SKTXN_SLSDTLS;
ALTER TABLE TKTXN_SLSHDRS RENAME TO SKTXN_SLSHDRS;
ALTER TABLE TKTXN_SLSKIRIMS RENAME TO SKTXN_SLSKIRIMS;
ALTER TABLE TKTXN_SLSPAYMENTS RENAME TO SKTXN_SLSPAYMENTS;
ALTER TABLE TKTXN_SOWHS RENAME TO SKTXN_SOWHS;
ALTER TABLE TKTXN_TUCASHINS RENAME TO SKTXN_TUCASHINS;
ALTER TABLE TKTXN_TUCASHOUTS RENAME TO SKTXN_TUCASHOUTS;

-- View (40)
RENAME DIVIEW_APPLICATIONS TO SKVIEW_APPLICATIONS;
RENAME RSVIEW_CHECKUPS TO SKVIEW_CHECKUPS;
RENAME RSVIEW_DASHBOARD10RJS TO SKVIEW_DASHBOARD10RJS;
RENAME RSVIEW_DASHBOARDKUNJ_C_LAB TO SKVIEW_DASHBOARDKUNJ_C_LAB;
RENAME RSVIEW_DASHBOARDKUNJ_C_LABX TO SKVIEW_DASHBOARDKUNJ_C_LABX;
RENAME RSVIEW_DASHBOARDKUNJ_D_LAB TO SKVIEW_DASHBOARDKUNJ_D_LAB;
RENAME RSVIEW_DASHBOARDKUNJ_D_LABX TO SKVIEW_DASHBOARDKUNJ_D_LABX;
RENAME RSVIEW_DASHBOARDSLANJUTAN TO SKVIEW_DASHBOARDSLANJUTAN;
RENAME RSVIEW_DASHBOARD_F20_HTCT TO SKVIEW_DASHBOARD_F20_HTCT;
RENAME RSVIEW_DASHBOARD_F20_JML TO SKVIEW_DASHBOARD_F20_JML;
RENAME RSVIEW_DB_RJS TO SKVIEW_DB_RJS;
RENAME RSVIEW_DRRJANTRIAN TO SKVIEW_DRRJANTRIAN;
RENAME RSVIEW_ERMSTATUS TO SKVIEW_ERMSTATUS;
RENAME RSVIEW_RADS TO SKVIEW_RADS;
RENAME RSVIEW_RJKASIR TO SKVIEW_RJKASIR;
RENAME RSVIEW_RJRADS TO SKVIEW_RJRADS;
RENAME RSVIEW_RJREGS TO SKVIEW_RJREGS;
RENAME RSVIEW_RJSTRS TO SKVIEW_RJSTRS;
RENAME RSVIEW_RJUPLOADBPJSES TO SKVIEW_RJUPLOADBPJSES;
RENAME RSVIEW_RSLABS TO SKVIEW_RSLABS;
RENAME SCVIEW_SCPOLIS TO SKVIEW_SCPOLIS;
RENAME TKVIEW_ACCOUNTS TO SKVIEW_ACCOUNTS;
RENAME TKVIEW_ACCOUNTS_LABARUGI TO SKVIEW_ACCOUNTS_LABARUGI;
RENAME TKVIEW_ACCOUNTS_NERACA TO SKVIEW_ACCOUNTS_NERACA;
RENAME TKVIEW_ACCTEMPLATE TO SKVIEW_ACCTEMPLATE;
RENAME TKVIEW_HPPES TO SKVIEW_HPPES;
RENAME TKVIEW_IOHUTANGS TO SKVIEW_IOHUTANGS;
RENAME TKVIEW_IOPIUTANGS TO SKVIEW_IOPIUTANGS;
RENAME TKVIEW_IOSTOCKWHS TO SKVIEW_IOSTOCKWHS;
RENAME TKVIEW_LASTRCV TO SKVIEW_LASTRCV;
RENAME TKVIEW_RCVDTLS TO SKVIEW_RCVDTLS;
RENAME TKVIEW_RCVHDRS TO SKVIEW_RCVHDRS;
RENAME TKVIEW_RCVPAYS TO SKVIEW_RCVPAYS;
RENAME TKVIEW_SALDOAKHIRSTOCKS TO SKVIEW_SALDOAKHIRSTOCKS;
RENAME TKVIEW_SALDOAWALHUTANG TO SKVIEW_SALDOAWALHUTANG;
RENAME TKVIEW_SALDOAWALPIUTANG TO SKVIEW_SALDOAWALPIUTANG;
RENAME TKVIEW_SALDOAWALSTOCKS TO SKVIEW_SALDOAWALSTOCKS;
RENAME TKVIEW_SALDOSTOCK_LIST TO SKVIEW_SALDOSTOCK_LIST;
RENAME TKVIEW_SLSHDRS TO SKVIEW_SLSHDRS;
RENAME TKVIEW_SLSPAYS TO SKVIEW_SLSPAYS;

-- Setelah ini teks view masih merujuk nama lama → INVALID.
-- Jalankan 02 (synonym) supaya view bisa compile, ATAU langsung 03 (recreate).
